import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { readFile, writeFile, access } from 'node:fs/promises';
import { build } from '/srv/shared/code/neutron/node_modules/esbuild/lib/main.js';
import { sassPlugin } from '/srv/shared/code/neutron/node_modules/esbuild-sass-plugin/lib/index.js';
import { chromium } from '/srv/shared/code/neutron/node_modules/playwright/index.mjs';
const root='/srv/shared/code/neutron',out='/tmp/neutron-bridge-dismiss-browser';
const checks=[],errors=[];
const bootstrap=`import React from 'react'; import { createRoot } from 'react-dom/client'; import { WalletBridgeDeposit } from '${root}/apps/wallet/src/bridge_control.tsx'; import '${root}/apps/wallet/src/style.scss'; createRoot(document.getElementById('root')).render(<main className="nt-app wallet-app" style={{padding:16,overflow:'auto',height:'100dvh',boxSizing:'border-box'}}><section style={{maxWidth:440,margin:'0 auto',minWidth:0}}><h2 style={{fontSize:18,margin:'0 0 18px'}}>Receive ckUSDC</h2><WalletBridgeDeposit ledger="xevnm-gaaaa-aaaar-qafnq-cai" symbol="ckUSDC" decimals={6} onRefresh={()=>window.__bridgeHarness.refreshes++} tray={false} openInTile={async()=>{}} /></section></main>);`;
await build({absWorkingDir:root,entryPoints:['bridge-dismiss-entry'],outfile:`${out}/main.js`,bundle:true,platform:'browser',format:'esm',jsx:'automatic',logLevel:'warning',plugins:[{name:'bridge-dismiss-boundaries',setup(b){b.onResolve({filter:/^bridge-dismiss-entry$/},()=>({path:'entry',namespace:'fixture-entry'}));b.onLoad({filter:/.*/,namespace:'fixture-entry'},()=>({contents:bootstrap,loader:'tsx',resolveDir:root}));b.onResolve({filter:/^neutron-tools\/(app|evm_wallet)$/},()=>({path:`${out}/fixture.ts`}));}},sassPlugin()]});
const html='<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width, initial-scale=1"><link rel="stylesheet" href="/main.css"></head><body><div id="root"></div><script type="module" src="/main.js"></script></body></html>';
const server=createServer(async(req,res)=>{try{if(req.url==='/favicon.ico'){res.writeHead(204).end();return;}const file=req.url==='/main.js'?['main.js','text/javascript']:req.url==='/main.css'?['main.css','text/css']:null;res.setHeader('Content-Type',file?.[1]??'text/html');res.end(file?await readFile(`${out}/${file[0]}`):html);}catch(error){res.writeHead(500).end(String(error));}});
await new Promise(done=>server.listen(0,'127.0.0.1',done));
let executablePath;try{await access('/run/current-system/sw/bin/google-chrome-stable');executablePath='/run/current-system/sw/bin/google-chrome-stable';}catch{}
const browser=await chromium.launch({headless:true,...(executablePath?{executablePath}:{}),args:['--no-sandbox']});
const id=n=>n.toString(16).padStart(32,'0');
try{
 for(const width of [375,700]){
  const context=await browser.newContext({viewport:{width,height:900}}),page=await context.newPage();
  page.on('pageerror',e=>errors.push(String(e)));
  await page.route('**/*',route=>new URL(route.request().url()).hostname==='127.0.0.1'?route.continue():route.abort());
  const snapshot=()=>page.evaluate(()=>window.__bridgeHarness.snapshot());
  const settled=()=>page.getByRole('textbox',{name:'Amount of USDC to deposit',exact:true}).waitFor();
  const checkLayout=async()=>{assert.equal(await page.locator('button button').count(),0,'No nested buttons');assert.equal(await page.evaluate(()=>document.querySelector('main').scrollWidth>innerWidth),false,'No horizontal overflow');};
  const assertOnlyDismiss=async(before,dismissed,recordId)=>{
   const after=await snapshot(),delta=after.calls.slice(before.calls.length);
   assert.equal(delta.length,1,'Action only invokes one local write');
   assert.equal(delta[0].method,'wallet_bridge_step_v2');
   assert.equal(delta[0].args[0].dismiss.dismissed,dismissed);
   assert.equal(Object.values(delta[0].args[0].dismiss.id).map(x=>x.toString(16).padStart(2,'0')).join(''),recordId);
   assert.deepEqual(after.records,before.records,'Original journal bytes are unchanged');
  };
  await page.goto(`http://127.0.0.1:${server.address().port}`);
  await settled();await page.getByRole('button',{name:'2 deposits to continue',exact:true}).waitFor();
  await checkLayout();await page.screenshot({path:`${out}/${width}-saved-reminders.png`,fullPage:true});
  await page.getByRole('button',{name:'2 deposits to continue',exact:true}).click();
  await page.getByRole('button',{name:'Continue deposit',exact:true}).click();
  await page.getByRole('button',{name:'Dismiss',exact:true}).waitFor({state:'visible'});
  await page.waitForFunction(()=>window.__bridgeHarness.state.calls.some(x=>x.lane==='ethereum'));
  assert.match(await page.getByRole('alert').innerText(),/Could not check Ethereum/);
  await page.getByRole('button',{name:'Continue deposit',exact:true}).waitFor();
  assert.equal(await page.getByRole('button',{name:'Dismiss',exact:true}).isEnabled(),true);
  await checkLayout();await page.screenshot({path:`${out}/${width}-rpc-failed-dismiss.png`,fullPage:true});
  checks.push(`${width}: legacy confirmed approval and ready deposit reproduce Ethereum failure; enabled Dismiss is visible`);
  const beforeFirst=await snapshot();
  await page.getByRole('button',{name:'Dismiss',exact:true}).click();
  await settled();await page.getByRole('button',{name:'1 deposit to continue',exact:true}).waitFor();
  await assertOnlyDismiss(beforeFirst,true,id(1));
  const dismissed=page.locator('.wallet-bridge-dismissed');
  assert.equal(await dismissed.getAttribute('open'),null,'Dismissed starts collapsed');
  checks.push(`${width}: selected Dismiss makes one local canister write, clears reminder and preserves approval bytes`);
  const activity=page.locator('details.wallet-bridge-activity').filter({has:page.locator('summary').filter({hasText:/^Activity/})});
  await activity.locator('summary').click();
  assert.equal(await activity.getByRole('button',{name:'Dismiss 3 ckUSDC deposit',exact:true}).count(),0);
  await checkLayout();
  const beforeUnknown=await snapshot();
  await page.getByRole('button',{name:'Dismiss 6 ckUSDC deposit',exact:true}).click();
  await page.waitForFunction(()=>window.__bridgeHarness.state.dismissed.length===2);
  await assertOnlyDismiss(beforeUnknown,true,id(2));
  assert.equal(await page.getByRole('button',{name:/deposit to continue/}).count(),0);
  checks.push(`${width}: row Dismiss hides unknown deposit without reconciling, resending or clearing its request ID`);
  await page.evaluate(()=>{window.__bridgeHarness.holdRefresh=true;window.dispatchEvent(new Event('focus'));});
  await page.waitForFunction(()=>window.__bridgeHarness.refreshPending===true);
  const beforeSubmitted=await snapshot();
  await page.getByRole('button',{name:'Dismiss 9 ckUSDC deposit',exact:true}).click();
  await page.waitForFunction(()=>window.__bridgeHarness.state.dismissed.length===3,null,{timeout:3000});
  await assertOnlyDismiss(beforeSubmitted,true,id(3));
  await page.waitForFunction(()=>!document.querySelector('details.wallet-bridge-activity:not(.wallet-bridge-dismissed)'));
  assert.equal(await page.locator('.wallet-bridge-attention').count(),0);
  await checkLayout();await page.screenshot({path:`${out}/${width}-all-dismissed.png`,fullPage:true});
  checks.push(`${width}: submitted deposit dismisses immediately even while Ethereum progress request is stuck`);
  const beforeReload=await snapshot();
  await page.reload();await settled();await page.waitForFunction(()=>document.querySelector('.wallet-bridge-dismissed'));
  const afterReload=await snapshot();
  assert.deepEqual(afterReload.dismissed,[id(1),id(2),id(3)]);
  assert.deepEqual(afterReload.records,beforeReload.records);
  assert.equal(afterReload.calls.slice(beforeReload.calls.length).every(x=>x.lane==='query'),true,'Reload only reads local journals/activity');
  assert.equal(await activity.count(),0);assert.equal(await page.locator('.wallet-bridge-attention').count(),0);
  assert.equal(await dismissed.getAttribute('open'),null,'Dismissed stays collapsed on reload');
  await page.evaluate(()=>window.dispatchEvent(new Event('focus')));
  await page.waitForTimeout(50);
  assert.equal((await snapshot()).calls.length,afterReload.calls.length,'Dismissed deposits do not poll Ethereum');
  checks.push(`${width}: dismissed preferences survive reload; hidden deposits generate no Ethereum refresh or reminder`);
  await dismissed.locator('summary').click();
  const textLayout=await dismissed.locator('.wallet-bridge-history-row').evaluateAll(rows=>rows.map(row=>({amount:row.querySelector('strong').getBoundingClientRect().toJSON(),date:row.querySelector('small').getBoundingClientRect().toJSON()})));
  assert.equal(textLayout.every(row=>row.date.y>=row.amount.y+row.amount.height-1),true,'Dismissed amount and date appear on separate readable lines');
  await checkLayout();await page.screenshot({path:`${out}/${width}-dismissed-recovery.png`,fullPage:true});
  const beforeRestore=await snapshot();
  await page.getByRole('button',{name:'Restore 6 ckUSDC deposit',exact:true}).click();
  await page.getByRole('button',{name:'Continue deposit',exact:true}).waitFor();
  await assertOnlyDismiss(beforeRestore,false,id(2));
  await page.locator('.wallet-bridge-details summary').click();
  assert.equal(await page.getByText(id(2),{exact:true}).isVisible(),true,'Restore selects original deposit ID');
  assert.equal(await page.getByText('0x'+'aa'.repeat(32),{exact:true}).isVisible(),true,'Original approval hash retained');
  await checkLayout();await page.screenshot({path:`${out}/${width}-restored-original.png`,fullPage:true});
  const final=await snapshot();
  assert.equal(final.calls.some(x=>x.lane==='financial'),false,'No financial requests');
  assert.equal(final.calls.some(x=>x.method==='wallet_bridge_prepare_v1'),false,'No duplicate prepare');
  assert.deepEqual(final.records,beforeFirst.records,'All original records retained exactly');
  checks.push(`${width}: Restore returns original saved deposit and approval hash without sending funds or duplicating work`);
  await writeFile(`${out}/${width}-calls.json`,JSON.stringify(final.calls,null,2));
  await context.close();
 }
 assert.deepEqual(errors,[],'No browser runtime errors');
 await writeFile(`${out}/results.json`,JSON.stringify({checks,errors,boundaries:'Real WalletBridgeDeposit, bridge client, execution and EVM bridge code. Mock local canister persistence and EVM tool boundary; Ethereum RPC is unavailable. No production mutations or real funds.'},null,2));
 console.log(JSON.stringify({checks,errors,output:out},null,2));
}finally{await browser.close();await new Promise(done=>server.close(done));}
