// All rights reserved. See ../LICENSE.
import Test "mo:test";
import Array "mo:core/Array";
import Blob "mo:core/Blob";
import Nat8 "mo:core/Nat8";
import Principal "mo:core/Principal";
import Runtime "mo:core/Runtime";
import Evidence "../mo/EvmEvidence";
import Rpc "../mo/EvmRpc";

persistent actor {
    // Independent ABI fixture: Keccak of the published event signature and
    // length-prefixed principal bytes, not output generated by the verifier.
    let signature = "0x918adbebdb8f3b36fc337ab76df10b147b2def5c9dd62cb3456d9aeca40e0b07";
    let recipientTopic = "0x0a00000000000000020101000000000000000000000000000000000000000000";
    let helper = "0x18901044688D3756C35Ed2b36D93e6a5B8e00E68";
    let token = "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48";
    let payer = "0xe70ab51ef2d86e70d834b4ac809d75e362ca23f2";
    let otherAddress = "0x1111111111111111111111111111111111111111";
    let tokenTopic = "0x000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48";
    let payerTopic = "0x000000000000000000000000e70ab51ef2d86e70d834b4ac809d75e362ca23f2";
    let otherAddressTopic = "0x0000000000000000000000001111111111111111111111111111111111111111";
    let transactionHash = "0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
    let blockHash = "0xbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb";
    let otherHash = "0xcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc";
    let amountWord = "00000000000000000000000000000000000000000000000000000000000f4240";
    let subaccountWord = "0000000000000000000000000000000000000000000000000000000000000009";
    let zeroWord = "0000000000000000000000000000000000000000000000000000000000000000";

    func expected() : Evidence.Expected {
        {
            chainId = 1; helper; token; payer;
            recipient = Principal.fromText("ryjl3-tyaaa-aaaaa-aaaba-cai");
            subaccount = Blob.fromArray(Array.tabulate<Nat8>(32, func(index) { if (index == 31) 9 else 0 }));
            amount = 1_000_000; transactionHash;
        };
    };
    func event() : Rpc.LogEntry {
        {
            transactionHash = ?transactionHash; blockNumber = ?25_000_000;
            data = "0x" # amountWord # subaccountWord; blockHash = ?blockHash;
            transactionIndex = ?2; topics = [signature, tokenTopic, payerTopic, recipientTopic];
            address = helper; logIndex = ?5; removed = false;
        };
    };
    func receipt() : Rpc.TransactionReceipt {
        {
            to = ?helper; status = ?1; root = null; transactionHash; blockNumber = 25_000_000;
            from = payer; logs = [event()]; blockHash; type_ = "0x2"; transactionIndex = 2;
            effectiveGasPrice = 1_000_000_000; logsBloom = "0x"; contractAddress = null;
            gasUsed = 100_000; cumulativeGasUsed = 300_000;
        };
    };
    func block() : Rpc.Block {
        {
            miner = otherAddress; totalDifficulty = null; receiptsRoot = otherHash; stateRoot = otherHash;
            hash = blockHash; difficulty = null; size = 500; uncles = []; baseFeePerGas = ?1_000_000;
            extraData = "0x"; transactionsRoot = ?otherHash; sha3Uncles = otherHash; nonce = 0;
            number = 25_000_000; timestamp = 1_788_991_000; transactions = [transactionHash];
            gasLimit = 30_000_000; logsBloom = "0x"; parentHash = otherHash; gasUsed = 300_000; mixHash = otherHash;
        };
    };
    func proof(value : Evidence.Result<Evidence.Proof>) : Evidence.Proof {
        switch value { case (#ok(result)) result; case (#err(error)) Runtime.trap(error) };
    };
    func rejected(value : Evidence.Result<Evidence.Proof>) {
        switch value { case (#err(error)) assert error.size() > 0; case (#ok(_)) assert false };
    };
    func rejectLog(log : Rpc.LogEntry) {
        let original = receipt();
        rejected(Evidence.verify(expected(), { original with logs = [log] }, block()));
    };

    public func exact_deposit_event_binds_invoice_and_replay_identity() : async Test.Metrics {
        Test.test(func () {
            assert Evidence.eventTopic == signature;
            assert Evidence.principalWord(expected().recipient) == recipientTopic;
            let result = proof(Evidence.verify(expected(), receipt(), block()));
            assert result == {
                eventKey = "1:" # transactionHash # ":5";
                transactionHash; logIndex = 5; blockNumber = 25_000_000;
                blockHash; payer; amount = 1_000_000;
            };
        });
    };

    public func every_invoice_binding_must_match() : async Test.Metrics {
        Test.test(func () {
            let invoice = expected();
            let invalid : [Evidence.Expected] = [
                { invoice with chainId = 42161 },
                { invoice with helper = otherAddress },
                { invoice with token = otherAddress },
                { invoice with payer = otherAddress },
                { invoice with recipient = Principal.fromText("rrkah-fqaaa-aaaaa-aaaaq-cai") },
                { invoice with subaccount = Blob.fromArray(Array.repeat<Nat8>(0, 32)) },
                { invoice with amount = 999_999 },
                { invoice with transactionHash = otherHash },
            ];
            for (value in invalid.vals()) rejected(Evidence.verify(value, receipt(), block()));
        });
    };

    public func validates_helper_event_signature_and_canonical_abi() : async Test.Metrics {
        Test.test(func () {
            let log = event();
            let invalid : [Rpc.LogEntry] = [
                { log with address = otherAddress },
                { log with topics = [otherHash, tokenTopic, payerTopic, recipientTopic] },
                { log with topics = [signature, tokenTopic, payerTopic] },
                { log with topics = [signature, tokenTopic, payerTopic, recipientTopic, otherHash] },
                { log with topics = [signature, "0x100000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48", payerTopic, recipientTopic] },
                { log with topics = [signature, tokenTopic, "0x100000000000000000000000e70ab51ef2d86e70d834b4ac809d75e362ca23f2", recipientTopic] },
                { log with topics = [signature, tokenTopic, payerTopic, "0x0a00000000000000020101000000000000000000000000000000000000000001"] },
                { log with topics = [signature, tokenTopic, otherAddressTopic, recipientTopic] },
                { log with data = "0x" # amountWord },
                { log with data = "0x" # amountWord # subaccountWord # "00" },
                { log with data = "0x" # amountWord # zeroWord },
                { log with data = "0x" # zeroWord # subaccountWord },
                { log with data = "0x" # amountWord # "g000000000000000000000000000000000000000000000000000000000000009" },
            ];
            for (value in invalid.vals()) rejectLog(value);
        });
    };

    public func removed_or_unbound_log_metadata_cannot_prove_payment() : async Test.Metrics {
        Test.test(func () {
            let log = event();
            let invalid : [Rpc.LogEntry] = [
                { log with removed = true },
                { log with logIndex = null },
                { log with transactionHash = null },
                { log with blockHash = null },
                { log with blockNumber = null },
                { log with transactionIndex = null },
                { log with transactionHash = ?otherHash },
                { log with blockHash = ?otherHash },
                { log with blockNumber = ?25_000_001 },
                { log with transactionIndex = ?3 },
            ];
            for (value in invalid.vals()) rejectLog(value);
        });
    };

    public func receipt_and_observed_block_must_agree() : async Test.Metrics {
        Test.test(func () {
            let original = receipt();
            let invalid : [Rpc.TransactionReceipt] = [
                { original with status = ?0 },
                { original with status = null },
                { original with status = ?2 },
                { original with transactionHash = otherHash },
                { original with blockHash = otherHash },
                { original with blockNumber = 25_000_001 },
                { original with logs = [] },
            ];
            for (value in invalid.vals()) rejected(Evidence.verify(expected(), value, block()));
            let observed = block();
            rejected(Evidence.verify(expected(), original, { observed with hash = otherHash }));
            rejected(Evidence.verify(expected(), original, { observed with number = 25_000_001 }));
        });
    };

    public func malformed_invoice_inputs_are_rejected_without_traps() : async Test.Metrics {
        Test.test(func () {
            let invoice = expected();
            let invalid : [Evidence.Expected] = [
                { invoice with helper = "0x1234" },
                { invoice with payer = "0x000000000000000000000000000000000000000g" },
                { invoice with transactionHash = "0x01" },
                { invoice with subaccount = Blob.fromArray([]) },
                { invoice with subaccount = Blob.fromArray(Array.repeat<Nat8>(0, 33)) },
                { invoice with amount = 0 },
                { invoice with amount = 2 ** 256 },
            ];
            for (value in invalid.vals()) rejected(Evidence.verify(value, receipt(), block()));
        });
    };

    public func duplicate_deposits_require_explicit_selection() : async Test.Metrics {
        Test.test(func () {
            let original = receipt();
            let log = event();
            rejected(Evidence.verify(expected(), { original with logs = [log, log] }, block()));
            rejected(Evidence.verify(expected(), { original with logs = [log, { log with logIndex = ?6 }] }, block()));
            let unrelated : Rpc.LogEntry = { log with address = token; topics = [otherHash] };
            let result = proof(Evidence.verify(expected(), { original with logs = [unrelated, log] }, block()));
            assert result.logIndex == 5;
        });
    };

    public func helper_owner_remains_payer_when_transaction_is_relayed() : async Test.Metrics {
        Test.test(func () {
            // A contract wallet can call the helper through a bundler/relayer.
            // Transaction sender and top-level destination are not its indexed owner.
            let original = receipt();
            let relayed = { original with from = otherAddress; to = ?otherAddress };
            assert proof(Evidence.verify(expected(), relayed, block())).payer == payer;
            let log = event();
            rejected(Evidence.verify(expected(), { relayed with logs = [{ log with topics = [signature, tokenTopic, otherAddressTopic, recipientTopic] }] }, block()));
        });
    };

    public func multicall_other_deposits_do_not_hide_exact_invoice() : async Test.Metrics {
        Test.test(func () {
            let original = receipt();
            let log = event();
            let other = { log with logIndex = ?6 };
            let otherPrincipal = Evidence.principalWord(Principal.fromText("rrkah-fqaaa-aaaaa-aaaaq-cai"));
            let unrelated : [Rpc.LogEntry] = [
                { other with topics = [signature, otherAddressTopic, payerTopic, recipientTopic] },
                { other with topics = [signature, tokenTopic, otherAddressTopic, recipientTopic] },
                { other with topics = [signature, tokenTopic, payerTopic, otherPrincipal] },
                { other with data = "0x00000000000000000000000000000000000000000000000000000000000f4241" # subaccountWord },
                { other with data = "0x" # amountWord # zeroWord },
                // Malformed other logs cannot supply a second exact match.
                { other with topics = [signature, otherAddressTopic]; data = "0xdeadbeef" },
                { other with topics = [signature, tokenTopic, otherAddressTopic, recipientTopic]; data = "0xdeadbeef" },
                { other with topics = [signature, "0x100000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48", payerTopic, recipientTopic] },
            ];
            for (unmatched in unrelated.vals()) {
                let before = proof(Evidence.verify(expected(), { original with logs = [unmatched, log] }, block()));
                let after = proof(Evidence.verify(expected(), { original with logs = [log, unmatched] }, block()));
                assert before == after;
                assert before.logIndex == 5 and before.eventKey == "1:" # transactionHash # ":5";
            };
        });
    };
}
