import Blob "mo:core/Blob";
import Principal "mo:core/Principal";
import Memory "../backend/memory/state/v1";
import App "../backend/main";
import Capabilities "mo:neutron-capabilities";

let owner = Principal.fromText("rrkah-fqaaa-aaaaa-aaaaq-cai");
let broker : Capabilities.BackendCallsV1 = {
    canister_principal = owner;
    can_call = func(_canister : Principal, _method : Text) : Bool { true };
    call = func(_request : Capabilities.BackendCallRequestV1) : async* Capabilities.BackendCallResultV1 { #err({ code = "test"; message = "No network" }) };
    call_batch = func(_requests : [Capabilities.BackendCallRequestV1]) : async* [Capabilities.BackendCallResultV1] { [] };
};
let memory = Memory.init();
let app = App.Init({ stable_memory = { state = memory }; capabilities = { backend_calls = broker } });
assert app.marketplace_state(()).canister == null;
assert app.marketplace_state(()).seed == null;
switch (app.marketplace_initialize(Blob.fromArray([1, 2]))) { case (#err(_)) {}; case (_) assert false };
let seed : Blob = "01234567890123456789012345678901";
ignore app.marketplace_initialize(seed);
ignore app.marketplace_initialize("11234567890123456789012345678901");
assert app.marketplace_state(()).seed == ?seed;
ignore app.marketplace_save_draft({ id = "purchase-1"; value = "original" });
switch (app.marketplace_save_draft({ id = "purchase-1"; value = "replacement" })) { case (#err(_)) {}; case (_) assert false };
assert app.marketplace_draft("purchase-1") == ?"original";
let restored = App.Init({ stable_memory = { state = memory }; capabilities = { backend_calls = broker } });
assert restored.marketplace_state(()).seed == ?seed;
assert restored.marketplace_draft("purchase-1") == ?"original";
assert restored.marketplace_drafts({ cursor = null; limit = 1 }).items.size() == 1;
ignore app.marketplace_save_draft({ id = "purchase-2"; value = "second" });
let firstPage = restored.marketplace_drafts({ cursor = null; limit = 1 });
assert firstPage.nextCursor == ?"purchase-1";
let secondPage = restored.marketplace_drafts({ cursor = firstPage.nextCursor; limit = 1 });
assert secondPage.items[0].id == "purchase-2";
assert secondPage.items[0].value == "second";
assert secondPage.nextCursor == null;
// Revisions preserve the previous bytes and compare the exact expected value.
switch (restored.marketplace_revise_draft({ id = "purchase-1"; expected = "wrong"; value = "changed"; revision = "revision-1" })) { case (#err(_)) {}; case (_) assert false };
assert restored.marketplace_draft("purchase-1") == ?"original";
ignore restored.marketplace_revise_draft({ id = "purchase-1"; expected = "original"; value = "changed"; revision = "revision-1" });
assert restored.marketplace_draft("purchase-1") == ?"changed";
assert restored.marketplace_draft("history:purchase-1:revision-1") == ?"original";
ignore restored.marketplace_revise_draft({ id = "purchase-1"; expected = "original"; value = "changed"; revision = "revision-1" });
switch (restored.marketplace_revise_draft({ id = "purchase-1"; expected = "original"; value = "competing"; revision = "revision-2" })) { case (#err(_)) {}; case (_) assert false };
assert restored.marketplace_draft("purchase-1") == ?"changed";
let restoredRevision = App.Init({ stable_memory = { state = memory }; capabilities = { backend_calls = broker } });
assert restoredRevision.marketplace_draft("history:purchase-1:revision-1") == ?"original";
assert App.allowed("purchase");
assert App.allowed("ethereum_prepare");
assert App.allowed("ethereum_verify");
assert App.allowed("ethereum_settle");
assert App.allowed("ethereum_cancel");
assert not App.allowed("ethereum_status");
assert not App.allowed("ethereum_history");
assert not App.allowed("icrc1_transfer");
assert not App.allowed("catalog");
