// Generated by connections/generate.ts. Do not edit.
export const generatedConnectionProviders = [
  {
    "id": "openrouter",
    "name": "OpenRouter",
    "description": "OpenRouter models and user-controlled API key",
    "authorizationOrigin": "https://openrouter.ai",
    "scopes": []
  }
] as const;
