import assert from "node:assert/strict";

/** Exercise codepoint limits through real inputs and the mock protocol boundary. */
export async function testFeedbackTextLimits({ page, fresh, button, openThread, screenshots, callCount, lastCall, checks }) {
  const emoji = "🧭";
  const titleAtLimit = emoji.repeat(160), titleOverLimit = emoji.repeat(161);
  const bodyAtLimit = emoji.repeat(16_000), bodyOverLimit = emoji.repeat(16_001);
  const numberPattern = value => value.toLocaleString("en-US").replaceAll(",", ",?");
  const counter = (count, maximum) => page.getByText(new RegExp(`^${numberPattern(count)}\\s*/\\s*${numberPattern(maximum)}(?:\\s+characters)?$`));
  const beginIssue = async () => {
    await fresh();
    await button("New message").click();
    await page.getByRole("button", { name: "Report a problem", exact: true }).click();
  };
  const submitIfEnabled = async name => { const submit = button(name); if (await submit.isEnabled()) await submit.click(); };
  const title = () => page.getByRole("textbox", { name: "Title", exact: true });
  const body = () => page.getByRole("textbox", { name: "Message", exact: true });

  await beginIssue();
  await title().fill(titleOverLimit);
  await body().fill("This body fits within the limit.");
  await submitIfEnabled("Send ticket");
  assert.equal(await callCount("create"), 0, "161 emoji must be rejected in the UI before a create call");
  assert.equal(await title().inputValue(), titleOverLimit, "a pasted over-limit title remains intact");
  assert.equal(await title().getAttribute("maxlength"), null, "native UTF-16 truncation must not clip emoji titles");
  assert.equal(await title().getAttribute("aria-invalid"), "true");
  await counter(161, 160).waitFor();
  await page.getByText("Title must be 160 characters or fewer. Remove 1 character to continue.", { exact: true }).waitFor();
  await screenshots("invalid-title");
  await title().fill(titleAtLimit);
  await counter(160, 160).waitFor();
  await button("Send ticket").click();
  await page.getByRole("heading", { name: titleAtLimit, exact: true }).waitFor();
  assert.equal((await lastCall("create"))[1].title, titleAtLimit, "160 emoji reach the protocol as exactly 160 codepoints");
  checks.push("Titles count emoji as one codepoint: 160 are accepted, 161 are rejected before a client call, and the full pasted value remains editable without maxlength truncation.");

  await beginIssue();
  await title().fill("A full-length message");
  await body().fill(bodyOverLimit);
  await submitIfEnabled("Send ticket");
  assert.equal(await callCount("create"), 0, "16,001 emoji must be rejected before a create call");
  assert.equal(await body().inputValue(), bodyOverLimit);
  assert.equal(await body().getAttribute("maxlength"), null);
  assert.equal(await body().getAttribute("aria-invalid"), "true");
  await counter(16_001, 16_000).waitFor();
  await page.getByText("Message must be 16,000 characters or fewer. Remove 1 character to continue.", { exact: true }).waitFor();
  await screenshots("invalid-message");
  await body().fill(bodyAtLimit);
  await counter(16_000, 16_000).waitFor();
  await button("Send ticket").click();
  await page.getByRole("heading", { name: "A full-length message", exact: true }).waitFor();
  assert.equal((await lastCall("create"))[1].body, bodyAtLimit);
  checks.push("Messages accept exactly 16,000 emoji, reject 16,001 before a client call, show codepoint counters, and preserve the entire over-limit draft.");

  for (const moderator of [false, true]) {
    await fresh(moderator ? "?moderator" : "");
    if (moderator) await button("Moderator inbox").click();
    const threadTitle = moderator ? "Wallet balance is not refreshing" : "Shared file link will not open";
    await openThread(threadTitle);
    const reply = page.getByRole("textbox", { name: moderator ? "Reply as support" : "Your reply", exact: true });
    const method = moderator ? "moderationReply" : "reply";
    const submit = moderator ? "Reply as support" : "Send reply";
    await reply.fill(bodyOverLimit);
    await submitIfEnabled(submit);
    assert.equal(await callCount(method), 0, `${method} must block an over-limit new draft before calling its client`);
    assert.equal(await reply.inputValue(), bodyOverLimit);
    assert.equal(await reply.getAttribute("maxlength"), null);
    assert.equal(await reply.getAttribute("aria-invalid"), "true");
    await counter(16_001, 16_000).waitFor();
    await page.getByText("Reply must be 16,000 characters or fewer. Remove 1 character to continue.", { exact: true }).waitFor();
    await screenshots(moderator ? "invalid-support-reply" : "invalid-reply");
    await reply.fill(bodyAtLimit);
    await counter(16_000, 16_000).waitFor();
    await button(submit).click();
    await page.waitForFunction(name => window.__feedbackTest.calls.some(call => call[0] === name), method);
    assert.equal((await lastCall(method))[1].body, bodyAtLimit);
    await page.waitForFunction(() => document.querySelector("#feedback-reply")?.value === "");
    assert.equal(await callCount(moderator ? "reply" : "moderationReply"), 0);
  }
  checks.push("User and support replies enforce the same 16,000-codepoint boundary, preserve pasted overflow, and send exact-limit text through the correct user or moderator method.");

  await fresh("?oversized-pending");
  const saved = page.getByRole("region", { name: "Saved sends", exact: true });
  const historicalTitle = "🪐".repeat(161), historicalBody = "🪐".repeat(16_001);
  const committed = saved.locator(".fb-saved-send").first();
  await committed.locator("summary").click();
  assert.equal(await committed.locator("summary").innerText(), historicalTitle);
  assert.equal(await committed.locator(".fb-saved-body").innerText(), historicalBody, "historical oversized pending text remains viewable in full");
  await committed.getByRole("button", { name: "Confirm send", exact: true }).click();
  await page.getByRole("heading", { name: historicalTitle, exact: true }).waitFor();
  assert.equal((await lastCall("resume"))[1], "saved-oversized-committed");
  assert.deepEqual((await lastCall("create"))[1], { requestId: "saved-oversized-committed", kind: "issue", appId: "files", title: historicalTitle, body: historicalBody });
  assert.equal(await page.evaluate(() => window.__feedbackTest.created.size), 1, "new limits must not prevent reconciliation of an older committed send");
  const uncommitted = saved.locator(".fb-saved-send").first();
  await uncommitted.locator("summary").click();
  assert.equal(await uncommitted.locator(".fb-saved-body").innerText(), historicalBody);
  await uncommitted.getByRole("button", { name: "Confirm send", exact: true }).click();
  await saved.getByText("Messages can contain up to 16,000 characters.", { exact: true }).waitFor();
  assert.equal((await lastCall("resume"))[1], "saved-oversized-uncommitted");
  assert.deepEqual((await lastCall("reply"))[1], { requestId: "saved-oversized-uncommitted", threadId: "1", body: historicalBody });
  assert.equal(await page.evaluate(() => window.__feedbackTest.pendingRequests.size), 1, "an oversized historical draft remains recoverable after a definitive length rejection");
  assert.equal(await saved.locator(".fb-saved-body").innerText(), historicalBody);
  assert.equal(await page.evaluate(() => window.__feedbackTest.messages["1"].some(message => message.body.length > 32_000)), false);
  checks.push("Historical oversized saved sends remain inspectable and replay exact original bytes: an older committed create reconciles once, while an uncommitted reply reaches protocol validation and shows its definitive error.");

  const copyEditor = () => page.getByRole("region", { name: "Edit a copy", exact: true });
  const copySend = () => copyEditor().getByRole("button", { name: "Send edited copy", exact: true });
  const success = "Your edited copy was sent. The original saved message is unchanged.";
  await saved.getByRole("button", { name: "Edit a copy", exact: true }).click();
  await page.waitForFunction(() => {
    const editor = document.querySelector('[aria-label="Edit a copy"]');
    const active = document.activeElement;
    if (!editor?.contains(active)) return false;
    const field = active.getBoundingClientRect();
    const viewport = editor.closest(".fb-body").getBoundingClientRect();
    return field.top >= viewport.top && field.bottom <= viewport.bottom;
  });
  const copiedReply = () => copyEditor().getByRole("textbox", { name: "Your reply", exact: true });
  assert.equal(await copiedReply().inputValue(), historicalBody);
  assert.equal(await copiedReply().isEditable(), true);
  assert.equal(await copySend().isDisabled(), true, "the full original is editable but remains too long to send as a new copy");
  await copiedReply().fill("A shorter copy of the saved reply.");
  await screenshots("edited-copy");
  await page.evaluate(() => { window.__feedbackTest.failNextReply = true; });
  await copySend().click();
  await copyEditor().getByText("Reply confirmation was lost. Your draft is saved; try again.", { exact: true }).waitFor();
  const firstCopyReply = (await lastCall("reply"))[1];
  assert.notEqual(firstCopyReply.requestId, "saved-oversized-uncommitted");
  assert.equal(firstCopyReply.threadId, "1");
  assert.equal(firstCopyReply.body, "A shorter copy of the saved reply.");
  assert.equal(await copiedReply().isEditable(), false, "an unknown copy outcome protects its exact payload for replay");
  await copyEditor().getByRole("button", { name: "Close copy editor", exact: true }).click();
  await button("Continue editing copy").click();
  await page.waitForFunction(() => document.querySelector('[aria-label="Edit a copy"]')?.contains(document.activeElement));
  assert.equal(await copiedReply().inputValue(), "A shorter copy of the saved reply.");
  assert.equal(await copiedReply().isEditable(), false);
  await copySend().click();
  await page.getByText(success, { exact: true }).waitFor();
  await copyEditor().waitFor({ state: "detached" });
  assert.deepEqual((await lastCall("reply"))[1], firstCopyReply, "uncertain copy retries reuse the same new ID and body");
  assert.equal(await page.evaluate(() => window.__feedbackTest.messages["1"].filter(message => message.body === "A shorter copy of the saved reply.").length), 1);
  assert.equal(await page.evaluate(() => window.__feedbackTest.pendingRequests.get("saved-oversized-uncommitted").body), historicalBody);
  assert.equal(await page.evaluate(() => window.__feedbackTest.pendingRequests.size), 1);
  checks.push("Edit a copy brings its field into view and focuses it after expanded oversized text, keeps the original intact, and preserves the fresh copy's exact retry identity and readonly payload through an unknown response and close/reopen.");

  await fresh("?oversized-pending");
  await button("New message").click();
  await page.getByRole("button", { name: "Report a problem", exact: true }).click();
  const ordinary = page.getByRole("region", { name: "New message", exact: true });
  await ordinary.getByRole("textbox", { name: "Title", exact: true }).fill("Keep my separate unsent title");
  await ordinary.getByRole("textbox", { name: "Message", exact: true }).fill("Keep my separate unsent body.");
  await saved.locator(".fb-saved-send").first().getByRole("button", { name: "Edit a copy", exact: true }).click();
  assert.equal(await copyEditor().getByRole("textbox", { name: "Title", exact: true }).inputValue(), historicalTitle);
  assert.equal(await copyEditor().getByRole("textbox", { name: "Message", exact: true }).inputValue(), historicalBody);
  await copyEditor().getByRole("textbox", { name: "Title", exact: true }).fill("An edited copy of my Files report");
  await copyEditor().getByRole("textbox", { name: "Message", exact: true }).fill("The shorter explanation of my original report.");
  assert.equal(await ordinary.getByRole("textbox", { name: "Title", exact: true }).inputValue(), "Keep my separate unsent title");
  assert.equal(await ordinary.getByRole("textbox", { name: "Message", exact: true }).inputValue(), "Keep my separate unsent body.");
  await copySend().click();
  await page.getByText(success, { exact: true }).waitFor();
  await page.getByRole("heading", { name: "An edited copy of my Files report", exact: true }).waitFor();
  const copiedCreate = (await lastCall("create"))[1];
  assert.notEqual(copiedCreate.requestId, "saved-oversized-committed");
  assert.deepEqual({ ...copiedCreate, requestId: "new-copy" }, { requestId: "new-copy", kind: "issue", appId: "files", title: "An edited copy of my Files report", body: "The shorter explanation of my original report." });
  assert.equal(await page.evaluate(() => window.__feedbackTest.pendingRequests.get("saved-oversized-committed").title), historicalTitle);
  assert.equal(await page.evaluate(() => window.__feedbackTest.pendingRequests.get("saved-oversized-committed").body), historicalBody);
  await button("New message").click();
  assert.equal(await ordinary.getByRole("textbox", { name: "Title", exact: true }).inputValue(), "Keep my separate unsent title");
  assert.equal(await ordinary.getByRole("textbox", { name: "Message", exact: true }).inputValue(), "Keep my separate unsent body.");
  checks.push("A copied create preserves the original kind and affected app, uses a fresh ID, leaves its original journal unchanged, and never overwrites a separate ordinary composer draft.");

  await fresh("?oversized-pending&moderator");
  const supportSource = saved.locator(".fb-saved-send").filter({ has: page.getByText("Your support reply", { exact: true }) });
  await supportSource.getByRole("button", { name: "Edit a copy", exact: true }).click();
  const supportCopy = copyEditor().getByRole("textbox", { name: "Reply as support", exact: true });
  assert.equal(await supportCopy.inputValue(), historicalBody);
  await supportCopy.fill("A shorter support response.");
  await copySend().click();
  await page.getByText(success, { exact: true }).waitFor();
  await page.getByRole("heading", { name: "Wallet balance is not refreshing", exact: true }).waitFor();
  const copiedSupport = (await lastCall("moderationReply"))[1];
  assert.notEqual(copiedSupport.requestId, "saved-oversized-support");
  assert.equal(copiedSupport.threadId, "5");
  assert.equal(copiedSupport.body, "A shorter support response.");
  assert.equal(await callCount("reply"), 0);
  assert.equal(await page.evaluate(() => window.__feedbackTest.messages["5"].at(-1).role), "moderator");
  assert.equal(await page.evaluate(() => window.__feedbackTest.pendingRequests.get("saved-oversized-support").body), historicalBody);

  await fresh("?oversized-pending&prototype-id");
  const inheritedNameSource = saved.locator(".fb-saved-send").filter({ has: page.getByText("Your reply", { exact: true }) });
  await inheritedNameSource.getByRole("button", { name: "Edit a copy", exact: true }).click();
  assert.equal(await copiedReply().inputValue(), historicalBody, "valid request ID constructor must not collide with JavaScript object properties");
  await copiedReply().fill("Copy from a request whose ID is constructor.");
  await copySend().click();
  await page.getByText(success, { exact: true }).waitFor();
  assert.equal((await lastCall("reply"))[1].body, "Copy from a request whose ID is constructor.");
  assert.equal(await page.evaluate(() => window.__feedbackTest.pendingRequests.get("constructor").body), historicalBody);

  await fresh("?oversized-pending");
  await saved.locator(".fb-saved-send").first().getByRole("button", { name: "Edit a copy", exact: true }).click();
  await copyEditor().getByRole("textbox", { name: "Title", exact: true }).fill("Keep editing after the original confirms");
  await copyEditor().getByRole("textbox", { name: "Message", exact: true }).fill("This copy remains an independent draft.");
  await copyEditor().getByRole("button", { name: "Close copy editor", exact: true }).click();
  await saved.locator(".fb-saved-send").first().getByRole("button", { name: "Confirm send", exact: true }).click();
  await page.getByRole("heading", { name: historicalTitle, exact: true }).waitFor();
  await button("Continue editing copy").click();
  assert.equal(await copyEditor().getByRole("textbox", { name: "Title", exact: true }).inputValue(), "Keep editing after the original confirms");
  assert.equal(await copyEditor().getByRole("textbox", { name: "Message", exact: true }).inputValue(), "This copy remains an independent draft.");
  checks.push("Support copies retain moderator authorship and their original thread; valid unusual request IDs remain editable, and independent copies survive separate original confirmation.");
}
