

// THIS FILE IS AUTOGENERATED
// YOU WILL GET TYPECHECK ERRORS HERE. DON'T EDIT IT
// INSTEAD EDIT YOUR MODULE OR neutron.json

import NeutronPrim "mo:prim";
import NeutronModule_a6_kernel "main";
import NeutronMemorySchema_a6_kernel_r6_kernel_v3 "memory/kernel/v3";
import NeutronMemorySchema_a6_kernel_r17_kernel_activation_v1 "memory/activation/v1";


shared({caller = NeutronInstaller}) persistent actor class Class<system>() = NeutronActor {


    // Compiler-owned public identity context. This persistent immutable value
    // is initialized only by a trusted fresh-install compile and restored by
    // Motoko before transient actor initialization on every compatible upgrade.
    let NeutronTrustedInstallationNetworkIdV1 : Blob = "\6c\77\71\93\cb\35\2f\cf\16\1a\fa\d6\9a\6d\ef\78\9c\4c\6e\bd\d1\fd\1a\9e\b9\8d\54\c9\a8\a0\1c\44";
    transient let NeutronCompiledInstallationNetworkIdV1 : Blob = "\6c\77\71\93\cb\35\2f\cf\16\1a\fa\d6\9a\6d\ef\78\9c\4c\6e\bd\d1\fd\1a\9e\b9\8d\54\c9\a8\a0\1c\44";
    transient let NeutronTrustedInstallationContextV1 = do {
        assert(NeutronTrustedInstallationNetworkIdV1.size() == 32);
        var NeutronInstallationNetworkIdNonzeroV1 = false;
        for (NeutronInstallationNetworkIdByteV1 in NeutronTrustedInstallationNetworkIdV1.vals()) {
            if (NeutronInstallationNetworkIdByteV1 != 0) {
                NeutronInstallationNetworkIdNonzeroV1 := true;
            };
        };
        assert(NeutronInstallationNetworkIdNonzeroV1);
        if (NeutronCompiledInstallationNetworkIdV1.size() != 0) {
            assert(NeutronCompiledInstallationNetworkIdV1.size() == 32);
            let NeutronCompiledInstallationNetworkIdValuesV1 =
                NeutronCompiledInstallationNetworkIdV1.vals();
            for (NeutronRetainedInstallationNetworkIdByteV1 in NeutronTrustedInstallationNetworkIdV1.vals()) {
                switch (NeutronCompiledInstallationNetworkIdValuesV1.next()) {
                    case (?NeutronCompiledInstallationNetworkIdByteV1) {
                        assert(
                            NeutronRetainedInstallationNetworkIdByteV1 ==
                            NeutronCompiledInstallationNetworkIdByteV1
                        );
                    };
                    case null assert(false);
                };
            };
            assert(NeutronCompiledInstallationNetworkIdValuesV1.next() == null);
        };
        { network_id = NeutronTrustedInstallationNetworkIdV1 };
    };



    type NeutronMemoryType_a6_kernel_r6_kernel = {
        #v3 : NeutronMemorySchema_a6_kernel_r6_kernel_v3.Mem;
    };

    let NeutronMemoryStore_a6_kernel_r6_kernel:NeutronMemoryType_a6_kernel_r6_kernel = #v3(NeutronMemorySchema_a6_kernel_r6_kernel_v3.init());

    transient let #v3(NeutronMemory_a6_kernel_r6_kernel) = NeutronMemoryStore_a6_kernel_r6_kernel;


    type NeutronMemoryType_a6_kernel_r17_kernel_activation = {
        #v1 : NeutronMemorySchema_a6_kernel_r17_kernel_activation_v1.Mem;
    };

    let NeutronMemoryStore_a6_kernel_r17_kernel_activation:NeutronMemoryType_a6_kernel_r17_kernel_activation = #v1(NeutronMemorySchema_a6_kernel_r17_kernel_activation_v1.init());

    transient let #v1(NeutronMemory_a6_kernel_r17_kernel_activation) = NeutronMemoryStore_a6_kernel_r17_kernel_activation;





    func NeutronCommitManagedMemoryRetirements(NeutronCommitDeploymentId : Text) : () {
        assert(NeutronCommitDeploymentId == "development");

    };


    transient let NeutronActiveAppInstanceInventory = [{ app_id = "kernel"; version = 322; capability_plan_fingerprint = "dbc8605823bf1cda3ddbd9bac95204f6ebc3a745d9070c0790eb5b7a41d1bb8f"; resident_frame_security = #credentialless_opaque_v1 }];




    transient let NeutronKernel = NeutronModule_a6_kernel.Init(NeutronMemory_a6_kernel_r6_kernel,NeutronMemory_a6_kernel_r17_kernel_activation,"development",NeutronActiveAppInstanceInventory,NeutronPrim.principalOfActor(NeutronActor));



      private func NeutronAppFunction_a6_kernel_r29_capability_authority_revision(NeutronRequest: NeutronModule_a6_kernel.capability_authority_revision_Input) :  NeutronModule_a6_kernel.capability_authority_revision_Output {
         NeutronKernel.capability_authority_revision(NeutronRequest)
      };


    public shared({ caller = NeutronCaller }) func kernel_authorized_add(NeutronRequest: NeutronModule_a6_kernel.kernel_authorized_add_Input) : async NeutronModule_a6_kernel.kernel_authorized_add_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
         NeutronKernel.kernel_authorized_add(NeutronRequest )
    };


    public shared({ caller = NeutronCaller }) func kernel_authorized_rem(NeutronRequest: NeutronModule_a6_kernel.kernel_authorized_rem_Input) : async NeutronModule_a6_kernel.kernel_authorized_rem_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
         NeutronKernel.kernel_authorized_rem(NeutronRequest ,NeutronCaller)
    };


      private func NeutronAppFunction_a6_kernel_r13_is_authorized(NeutronRequest: NeutronModule_a6_kernel.is_authorized_Input) :  NeutronModule_a6_kernel.is_authorized_Output {
         NeutronKernel.is_authorized(NeutronRequest)
      };


    public query({ caller = NeutronCaller }) func kernel_check_authorized(NeutronRequest: NeutronModule_a6_kernel.kernel_check_authorized_Input) : async NeutronModule_a6_kernel.kernel_check_authorized_Output {
         NeutronKernel.kernel_check_authorized(NeutronRequest ,NeutronCaller)
    };


    public shared({ caller = NeutronCaller }) func kernel_authorized_recover(NeutronRequest: NeutronModule_a6_kernel.kernel_authorized_recover_Input) : async NeutronModule_a6_kernel.kernel_authorized_recover_Output {
         NeutronKernel.kernel_authorized_recover(NeutronRequest ,NeutronCaller)
    };


    public shared({ caller = NeutronCaller }) func kernel_activation(NeutronRequest: NeutronModule_a6_kernel.kernel_activation_Input) : async NeutronModule_a6_kernel.kernel_activation_Output {
         NeutronKernel.kernel_activation(NeutronRequest ,NeutronCaller)
    };


    public shared({ caller = NeutronCaller }) func kernel_static(NeutronRequest: NeutronModule_a6_kernel.kernel_static_Input) : async NeutronModule_a6_kernel.kernel_static_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
         NeutronKernel.kernel_static(NeutronRequest )
    };


    public query({ caller = NeutronCaller }) func kernel_static_query(NeutronRequest: NeutronModule_a6_kernel.kernel_static_query_Input) : async NeutronModule_a6_kernel.kernel_static_query_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
         NeutronKernel.kernel_static_query(NeutronRequest )
    };


    public query({ caller = NeutronCaller }) func http_request(NeutronRequest: NeutronModule_a6_kernel.http_request_Input) : async NeutronModule_a6_kernel.http_request_Output {
         NeutronKernel.http_request(NeutronRequest ,NeutronActor)
    };


    public query({ caller = NeutronCaller }) func http_request_streaming_callback(NeutronRequest: NeutronModule_a6_kernel.http_request_streaming_callback_Input) : async NeutronModule_a6_kernel.http_request_streaming_callback_Output {
         NeutronKernel.http_request_streaming_callback(NeutronRequest )
    };


    public shared({ caller = NeutronCaller }) func http_request_update(NeutronRequest: NeutronModule_a6_kernel.http_request_update_Input) : async NeutronModule_a6_kernel.http_request_update_Output {
        await* NeutronKernel.http_request_update(NeutronRequest ,NeutronCaller)
    };


    public query({ caller = NeutronCaller }) func kernel_https_outcall_transform(NeutronRequest: NeutronModule_a6_kernel.kernel_https_outcall_transform_Input) : async NeutronModule_a6_kernel.kernel_https_outcall_transform_Output {
         NeutronKernel.kernel_https_outcall_transform(NeutronRequest ,NeutronCaller)
    };


    public shared({ caller = NeutronCaller }) func kernel_install_begin_checked(NeutronRequest: NeutronModule_a6_kernel.kernel_install_begin_checked_Input) : async NeutronModule_a6_kernel.kernel_install_begin_checked_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
         NeutronKernel.kernel_install_begin_checked(NeutronRequest )
    };


    public query({ caller = NeutronCaller }) func kernel_install_status(NeutronRequest: NeutronModule_a6_kernel.kernel_install_status_Input) : async NeutronModule_a6_kernel.kernel_install_status_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
         NeutronKernel.kernel_install_status(NeutronRequest )
    };


    public query({ caller = NeutronCaller }) func kernel_settings_snapshot(NeutronRequest: NeutronModule_a6_kernel.kernel_settings_snapshot_Input) : async NeutronModule_a6_kernel.kernel_settings_snapshot_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
         NeutronKernel.kernel_settings_snapshot(NeutronRequest )
    };


    public query({ caller = NeutronCaller }) func kernel_certified_assets_scope_info(NeutronRequest: NeutronModule_a6_kernel.kernel_certified_assets_scope_info_Input) : async NeutronModule_a6_kernel.kernel_certified_assets_scope_info_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
         NeutronKernel.kernel_certified_assets_scope_info(NeutronRequest )
    };


    public query({ caller = NeutronCaller }) func kernel_certified_assets_usage(NeutronRequest: NeutronModule_a6_kernel.kernel_certified_assets_usage_Input) : async NeutronModule_a6_kernel.kernel_certified_assets_usage_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
         NeutronKernel.kernel_certified_assets_usage(NeutronRequest )
    };


    public query({ caller = NeutronCaller }) func kernel_certified_assets_diagnostics(NeutronRequest: NeutronModule_a6_kernel.kernel_certified_assets_diagnostics_Input) : async NeutronModule_a6_kernel.kernel_certified_assets_diagnostics_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
         NeutronKernel.kernel_certified_assets_diagnostics(NeutronRequest )
    };


    public query({ caller = NeutronCaller }) func kernel_certified_assets_audit_content_ownership_page(NeutronRequest: NeutronModule_a6_kernel.kernel_certified_assets_audit_content_ownership_page_Input) : async NeutronModule_a6_kernel.kernel_certified_assets_audit_content_ownership_page_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
         NeutronKernel.kernel_certified_assets_audit_content_ownership_page(NeutronRequest )
    };


    public query({ caller = NeutronCaller }) func kernel_certified_assets_audit_catalog_page(NeutronRequest: NeutronModule_a6_kernel.kernel_certified_assets_audit_catalog_page_Input) : async NeutronModule_a6_kernel.kernel_certified_assets_audit_catalog_page_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
         NeutronKernel.kernel_certified_assets_audit_catalog_page(NeutronRequest )
    };


    public shared({ caller = NeutronCaller }) func kernel_certified_assets_set_admission_ceilings(NeutronRequest: NeutronModule_a6_kernel.kernel_certified_assets_set_admission_ceilings_Input) : async NeutronModule_a6_kernel.kernel_certified_assets_set_admission_ceilings_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
         NeutronKernel.kernel_certified_assets_set_admission_ceilings(NeutronRequest )
    };


    public shared({ caller = NeutronCaller }) func kernel_certified_assets_set_writes_frozen(NeutronRequest: NeutronModule_a6_kernel.kernel_certified_assets_set_writes_frozen_Input) : async NeutronModule_a6_kernel.kernel_certified_assets_set_writes_frozen_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
         NeutronKernel.kernel_certified_assets_set_writes_frozen(NeutronRequest )
    };


    public shared({ caller = NeutronCaller }) func kernel_certified_assets_maintenance_page(NeutronRequest: NeutronModule_a6_kernel.kernel_certified_assets_maintenance_page_Input) : async NeutronModule_a6_kernel.kernel_certified_assets_maintenance_page_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
         NeutronKernel.kernel_certified_assets_maintenance_page(NeutronRequest )
    };


    public shared({ caller = NeutronCaller }) func kernel_certified_assets_retire_scope(NeutronRequest: NeutronModule_a6_kernel.kernel_certified_assets_retire_scope_Input) : async NeutronModule_a6_kernel.kernel_certified_assets_retire_scope_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
         NeutronKernel.kernel_certified_assets_retire_scope(NeutronRequest )
    };


    public shared({ caller = NeutronCaller }) func kernel_publication_entropy_initialize(NeutronRequest: NeutronModule_a6_kernel.kernel_publication_entropy_initialize_Input) : async NeutronModule_a6_kernel.kernel_publication_entropy_initialize_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
        await* NeutronKernel.kernel_publication_entropy_initialize(NeutronRequest )
    };


    public query({ caller = NeutronCaller }) func kernel_app_usage_snapshot(NeutronRequest: NeutronModule_a6_kernel.kernel_app_usage_snapshot_Input) : async NeutronModule_a6_kernel.kernel_app_usage_snapshot_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
         NeutronKernel.kernel_app_usage_snapshot(NeutronRequest )
    };


    public shared({ caller = NeutronCaller }) func kernel_memory_snapshot(NeutronRequest: NeutronModule_a6_kernel.kernel_memory_snapshot_Input) : async NeutronModule_a6_kernel.kernel_memory_snapshot_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
        await* NeutronKernel.kernel_memory_snapshot(NeutronRequest ,NeutronActor)
    };


    public query({ caller = NeutronCaller }) func kernel_backend_reservations_snapshot(NeutronRequest: NeutronModule_a6_kernel.kernel_backend_reservations_snapshot_Input) : async NeutronModule_a6_kernel.kernel_backend_reservations_snapshot_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
         NeutronKernel.kernel_backend_reservations_snapshot(NeutronRequest )
    };


    public query({ caller = NeutronCaller }) func kernel_scheduled_tasks_snapshot(NeutronRequest: NeutronModule_a6_kernel.kernel_scheduled_tasks_snapshot_Input) : async NeutronModule_a6_kernel.kernel_scheduled_tasks_snapshot_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
         NeutronKernel.kernel_scheduled_tasks_snapshot(NeutronRequest )
    };


    public query({ caller = NeutronCaller }) func kernel_capabilities_page(NeutronRequest: NeutronModule_a6_kernel.kernel_capabilities_page_Input) : async NeutronModule_a6_kernel.kernel_capabilities_page_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
         NeutronKernel.kernel_capabilities_page(NeutronRequest )
    };


    public shared({ caller = NeutronCaller }) func kernel_capability_set_enabled(NeutronRequest: NeutronModule_a6_kernel.kernel_capability_set_enabled_Input) : async NeutronModule_a6_kernel.kernel_capability_set_enabled_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
         NeutronKernel.kernel_capability_set_enabled(NeutronRequest ,NeutronCaller)
    };


    public shared({ caller = NeutronCaller }) func kernel_backend_reservations_apply(NeutronRequest: NeutronModule_a6_kernel.kernel_backend_reservations_apply_Input) : async NeutronModule_a6_kernel.kernel_backend_reservations_apply_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
         NeutronKernel.kernel_backend_reservations_apply(NeutronRequest ,NeutronCaller,NeutronActor)
    };


    public shared({ caller = NeutronCaller }) func kernel_install_reservations_prepare(NeutronRequest: NeutronModule_a6_kernel.kernel_install_reservations_prepare_Input) : async NeutronModule_a6_kernel.kernel_install_reservations_prepare_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
         NeutronKernel.kernel_install_reservations_prepare(NeutronRequest ,NeutronCaller)
    };


    public query({ caller = NeutronCaller }) func kernel_install_pending_reservation_blockers(NeutronRequest: NeutronModule_a6_kernel.kernel_install_pending_reservation_blockers_Input) : async NeutronModule_a6_kernel.kernel_install_pending_reservation_blockers_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
         NeutronKernel.kernel_install_pending_reservation_blockers(NeutronRequest )
    };


    public shared({ caller = NeutronCaller }) func kernel_install_pending_reservation_release(NeutronRequest: NeutronModule_a6_kernel.kernel_install_pending_reservation_release_Input) : async NeutronModule_a6_kernel.kernel_install_pending_reservation_release_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
         NeutronKernel.kernel_install_pending_reservation_release(NeutronRequest )
    };


    public shared({ caller = NeutronCaller }) func kernel_access_snapshot(NeutronRequest: NeutronModule_a6_kernel.kernel_access_snapshot_Input) : async NeutronModule_a6_kernel.kernel_access_snapshot_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
        await* NeutronKernel.kernel_access_snapshot(NeutronRequest ,NeutronActor)
    };


    public shared({ caller = NeutronCaller }) func kernel_controller_add(NeutronRequest: NeutronModule_a6_kernel.kernel_controller_add_Input) : async NeutronModule_a6_kernel.kernel_controller_add_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
        await* NeutronKernel.kernel_controller_add(NeutronRequest ,NeutronActor)
    };


    public shared({ caller = NeutronCaller }) func kernel_controller_rem(NeutronRequest: NeutronModule_a6_kernel.kernel_controller_rem_Input) : async NeutronModule_a6_kernel.kernel_controller_rem_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
        await* NeutronKernel.kernel_controller_rem(NeutronRequest ,NeutronActor)
    };


    public shared({ caller = NeutronCaller }) func kernel_install_commit(NeutronRequest: NeutronModule_a6_kernel.kernel_install_commit_Input) : async NeutronModule_a6_kernel.kernel_install_commit_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
         NeutronKernel.kernel_install_commit<system>(NeutronRequest ,NeutronCaller,NeutronCommitManagedMemoryRetirements)
    };


    public shared({ caller = NeutronCaller }) func kernel_install_abort(NeutronRequest: NeutronModule_a6_kernel.kernel_install_abort_Input) : async NeutronModule_a6_kernel.kernel_install_abort_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
        await* NeutronKernel.kernel_install_abort(NeutronRequest ,NeutronActor)
    };


    public shared({ caller = NeutronCaller }) func kernel_install_wasm_chunks_clear(NeutronRequest: NeutronModule_a6_kernel.kernel_install_wasm_chunks_clear_Input) : async NeutronModule_a6_kernel.kernel_install_wasm_chunks_clear_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
        await* NeutronKernel.kernel_install_wasm_chunks_clear(NeutronRequest ,NeutronActor)
    };


    public shared({ caller = NeutronCaller }) func kernel_install_wasm_chunk(NeutronRequest: NeutronModule_a6_kernel.kernel_install_wasm_chunk_Input) : async NeutronModule_a6_kernel.kernel_install_wasm_chunk_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
        await* NeutronKernel.kernel_install_wasm_chunk(NeutronRequest ,NeutronActor)
    };


    public shared({ caller = NeutronCaller }) func kernel_install_code_chunked(NeutronRequest: NeutronModule_a6_kernel.kernel_install_code_chunked_Input) : async NeutronModule_a6_kernel.kernel_install_code_chunked_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
        await* NeutronKernel.kernel_install_code_chunked(NeutronRequest ,NeutronActor)
    };


    public shared({ caller = NeutronCaller }) func kernel_install_code(NeutronRequest: NeutronModule_a6_kernel.kernel_install_code_Input) : async NeutronModule_a6_kernel.kernel_install_code_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
        await* NeutronKernel.kernel_install_code(NeutronRequest ,NeutronActor)
    };


    public shared({ caller = NeutronCaller }) func kernel_connections_begin(NeutronRequest: NeutronModule_a6_kernel.kernel_connections_begin_Input) : async NeutronModule_a6_kernel.kernel_connections_begin_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
        await* NeutronKernel.kernel_connections_begin(NeutronRequest ,NeutronCaller,NeutronActor)
    };


    public shared({ caller = NeutronCaller }) func kernel_connections_complete(NeutronRequest: NeutronModule_a6_kernel.kernel_connections_complete_Input) : async NeutronModule_a6_kernel.kernel_connections_complete_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
        await* NeutronKernel.kernel_connections_complete(NeutronRequest ,NeutronCaller)
    };


    public query({ caller = NeutronCaller }) func kernel_connections_list(NeutronRequest: NeutronModule_a6_kernel.kernel_connections_list_Input) : async NeutronModule_a6_kernel.kernel_connections_list_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
         NeutronKernel.kernel_connections_list(NeutronRequest ,NeutronCaller)
    };


    public shared({ caller = NeutronCaller }) func kernel_connections_acquire(NeutronRequest: NeutronModule_a6_kernel.kernel_connections_acquire_Input) : async NeutronModule_a6_kernel.kernel_connections_acquire_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
        await* NeutronKernel.kernel_connections_acquire(NeutronRequest ,NeutronCaller)
    };


    public shared({ caller = NeutronCaller }) func kernel_connections_disconnect(NeutronRequest: NeutronModule_a6_kernel.kernel_connections_disconnect_Input) : async NeutronModule_a6_kernel.kernel_connections_disconnect_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
        await* NeutronKernel.kernel_connections_disconnect(NeutronRequest ,NeutronCaller)
    };


    public query({ caller = NeutronCaller }) func kernel_vetkeys_list(NeutronRequest: NeutronModule_a6_kernel.kernel_vetkeys_list_Input) : async NeutronModule_a6_kernel.kernel_vetkeys_list_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
         NeutronKernel.kernel_vetkeys_list(NeutronRequest )
    };


    public query({ caller = NeutronCaller }) func kernel_vetkeys_binding(NeutronRequest: NeutronModule_a6_kernel.kernel_vetkeys_binding_Input) : async NeutronModule_a6_kernel.kernel_vetkeys_binding_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
         NeutronKernel.kernel_vetkeys_binding(NeutronRequest )
    };


    public shared({ caller = NeutronCaller }) func kernel_vetkeys_reserve(NeutronRequest: NeutronModule_a6_kernel.kernel_vetkeys_reserve_Input) : async NeutronModule_a6_kernel.kernel_vetkeys_reserve_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
        await* NeutronKernel.kernel_vetkeys_reserve(NeutronRequest ,NeutronCaller,NeutronActor)
    };


    public shared({ caller = NeutronCaller }) func kernel_vetkeys_enable(NeutronRequest: NeutronModule_a6_kernel.kernel_vetkeys_enable_Input) : async NeutronModule_a6_kernel.kernel_vetkeys_enable_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
         NeutronKernel.kernel_vetkeys_enable(NeutronRequest ,NeutronCaller)
    };


    public shared({ caller = NeutronCaller }) func kernel_vetkeys_disable(NeutronRequest: NeutronModule_a6_kernel.kernel_vetkeys_disable_Input) : async NeutronModule_a6_kernel.kernel_vetkeys_disable_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
         NeutronKernel.kernel_vetkeys_disable(NeutronRequest ,NeutronCaller)
    };


    public shared({ caller = NeutronCaller }) func kernel_vetkeys_rotate(NeutronRequest: NeutronModule_a6_kernel.kernel_vetkeys_rotate_Input) : async NeutronModule_a6_kernel.kernel_vetkeys_rotate_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
         NeutronKernel.kernel_vetkeys_rotate(NeutronRequest ,NeutronCaller)
    };


    public shared({ caller = NeutronCaller }) func kernel_vetkeys_retire_generation(NeutronRequest: NeutronModule_a6_kernel.kernel_vetkeys_retire_generation_Input) : async NeutronModule_a6_kernel.kernel_vetkeys_retire_generation_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
         NeutronKernel.kernel_vetkeys_retire_generation(NeutronRequest ,NeutronCaller)
    };


    public shared({ caller = NeutronCaller }) func kernel_vetkeys_transfer(NeutronRequest: NeutronModule_a6_kernel.kernel_vetkeys_transfer_Input) : async NeutronModule_a6_kernel.kernel_vetkeys_transfer_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
         NeutronKernel.kernel_vetkeys_transfer(NeutronRequest ,NeutronCaller)
    };


    public shared({ caller = NeutronCaller }) func kernel_vetkeys_retire_slot(NeutronRequest: NeutronModule_a6_kernel.kernel_vetkeys_retire_slot_Input) : async NeutronModule_a6_kernel.kernel_vetkeys_retire_slot_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
         NeutronKernel.kernel_vetkeys_retire_slot(NeutronRequest ,NeutronCaller)
    };


    public shared({ caller = NeutronCaller }) func kernel_vetkeys_public_key(NeutronRequest: NeutronModule_a6_kernel.kernel_vetkeys_public_key_Input) : async NeutronModule_a6_kernel.kernel_vetkeys_public_key_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
        await* NeutronKernel.kernel_vetkeys_public_key(NeutronRequest ,NeutronActor)
    };


    public shared({ caller = NeutronCaller }) func kernel_vetkeys_derive(NeutronRequest: NeutronModule_a6_kernel.kernel_vetkeys_derive_Input) : async NeutronModule_a6_kernel.kernel_vetkeys_derive_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
        await* NeutronKernel.kernel_vetkeys_derive(NeutronRequest ,NeutronCaller,NeutronActor)
    };


    public query({ caller = NeutronCaller }) func kernel_vetkeys_audit_snapshot(NeutronRequest: NeutronModule_a6_kernel.kernel_vetkeys_audit_snapshot_Input) : async NeutronModule_a6_kernel.kernel_vetkeys_audit_snapshot_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
         NeutronKernel.kernel_vetkeys_audit_snapshot(NeutronRequest )
    };


    public query({ caller = NeutronCaller }) func kernel_vetkeys_admin_snapshot(NeutronRequest: NeutronModule_a6_kernel.kernel_vetkeys_admin_snapshot_Input) : async NeutronModule_a6_kernel.kernel_vetkeys_admin_snapshot_Output {
        assert(NeutronKernel.is_authorized(NeutronCaller));
         NeutronKernel.kernel_vetkeys_admin_snapshot(NeutronRequest )
    };



    transient let NeutronAppScope_a6_kernel = NeutronKernel.app_scope("kernel", "development");

    NeutronKernel.configure_frontend_surface_counts({
      app_instances = 1;
      resident_frames = 0;
    });



    NeutronKernel.configure_app_capabilities([], {
      vetkeys_environment = #production;
      chain_key_signing_keys = {
      ecdsa_secp256k1 = ?"key_1";
      schnorr_bip340secp256k1 = ?"key_1";
      schnorr_ed25519 = ?"key_1";
    };
    });



    NeutronKernel.configure_capability_registry([], NeutronActor);








    public query({ caller = NeutronCaller }) func kernel_runtime_info() : async {
      deployment_id : Text;
      assembler_id : Text;
      compiler_id : Text;
      capability_authority_revision : ?Nat64;
      apps : [{
        scope : { app_id : Text; installation_uid : Nat64 };
        version : Nat;
        deployment_id : Text;
        capability_plan_fingerprint : Text;
        resident_frame_security : {
          #credentialless_opaque_v1;
          #credentialless_ephemeral_dedicated_v1;
          #persistent_dedicated_v1;
        };
        browser_origin_nonce : Text;
        browser_origin_authority_epoch : Nat64;
      }];
      memories : [{ id : Text; owner : Text; version : Nat; schema : Text }];
    } {
      assert(NeutronKernel.is_authorized(NeutronCaller));
      {
        deployment_id = "development";
        assembler_id = "neutron_actor_v26";
        compiler_id = "unknown";
        capability_authority_revision = ?NeutronKernel.capability_authority_revision();
        apps = NeutronKernel.runtime_app_instances("development");
        memories = [{ id = "kernel"; owner = "kernel"; version = 3; schema = "memory/kernel/v3" }, { id = "kernel_activation"; owner = "kernel"; version = 1; schema = "memory/activation/v1" }];
      }
    };


    NeutronKernel.kernel_authorized_add(NeutronInstaller);
}
