const owner='3rurp-vyaaa-aaaay-aacua-cai';
const state=window.__operating={calls:[],scenario:new URLSearchParams(location.search).get('scenario'),operations:JSON.parse(sessionStorage.getItem('operating-cycles-fixture')||'[]'),complete:false,balance:'55000000000000'};
if(state.scenario==='cycles-pages'&&state.operations.length===0)state.operations=Array.from({length:45},(_,index)=>({requestId:(100+index).toString(16).padStart(32,'0'),target:owner,requestedCyclesAtoms:'2000000000000',attachedCyclesAtoms:'2000000000000',expectedNetAtoms:'1999900000000',feeAtoms:'100000000',status:index===44?'pending':'complete',ledgerBlockIndex:index===44?null:String(99000+index),recipientBalanceAtoms:'50000000000000',error:null,createdAtNs:(1789110000000000000n-BigInt(index)).toString(),updatedAtNs:'1789110000000000000',refundedCyclesAtoms:'0',chargedCyclesAtoms:'2000000000000',allowPartial:false,detailsAvailable:true}));
const put=operation=>{state.operations=[operation,...state.operations.filter(row=>row.requestId!==operation.requestId)];sessionStorage.setItem('operating-cycles-fixture',JSON.stringify(state.operations));return structuredClone(operation);};
export async function loadOperatingCyclesSnapshot(requestedOwner,target=owner){state.calls.push({method:'snapshot',target});return{owner:requestedOwner,target,balanceAtoms:state.balance,reserveAtoms:'5000000000000',callCostAtoms:'5000000',maxCyclesAtoms:(BigInt(state.balance)-5000000000000n-5000000n).toString(),feeAtoms:'100000000',observedAt:1789110000000};}
export function quoteOperatingCyclesConversion(input,snapshot){if(input.target!==snapshot.target)throw Error("Refresh the conversion details for this recipient");const amount=BigInt(input.amountAtoms);const maximum=BigInt(snapshot.maxCyclesAtoms);if(amount>maximum&&!input.allowPartial)throw Error('Leave at least 5 T cycles plus network costs in your Neutron.');const actual=input.allowPartial&&amount>maximum?maximum:amount;if(actual<=BigInt(snapshot.feeAtoms))throw Error('Choose more than the TCYCLES minting fee.');return{...input,...snapshot,requestId:input.requestId,target:input.target,amountAtoms:input.amountAtoms,allowPartial:input.allowPartial,feeAtoms:snapshot.feeAtoms,expectedNetAtoms:(actual-BigInt(snapshot.feeAtoms)).toString(),remainingCyclesAtoms:(BigInt(snapshot.balanceAtoms)-actual-BigInt(snapshot.callCostAtoms)).toString()};}
export function isOperatingCyclesCancellation(error){return error?.code==='ONE_TIME_CYCLE_CALL_CANCELLED';}
export function isOperatingCyclesNotDispatched(error){return isOperatingCyclesCancellation(error)||error?.code==='ONE_TIME_CYCLE_CALL_NOT_DISPATCHED';}
export async function executeOperatingCyclesConversion(quote){state.calls.push({method:'review',quote});if(state.scenario==='cycles-preflight'&&state.calls.filter(row=>row.method==='review').length===1)throw Object.assign(Error('Permission check failed before dispatch. No cycles were sent.'),{code:'ONE_TIME_CYCLE_CALL_NOT_DISPATCHED'});return new Promise((resolve,reject)=>{
  const dialog=document.createElement('dialog');dialog.setAttribute('aria-label','Owner confirmation: convert Neutron cycles');dialog.style='background:#240d10;color:#fff;border:1px solid #d85d66;padding:20px;max-width:310px';
  const heading=document.createElement('h2');heading.textContent='Convert Neutron cycles';
  const description=document.createElement('p');description.textContent='This uses operating cycles from your Neutron. At least 5 T cycles remain.';
  const check=document.createElement('input');check.type='checkbox';check.id='owner-ack';const label=document.createElement('label');label.htmlFor=check.id;label.append(check,document.createTextNode('I understand this uses my Neutron cycles'));
  const cancel=document.createElement('button');cancel.textContent='Cancel owner approval';const confirm=document.createElement('button');confirm.textContent='Approve cycle conversion';confirm.disabled=true;
  check.onchange=()=>confirm.disabled=!check.checked;
  const close=()=>{dialog.close();dialog.remove();};cancel.onclick=()=>{close();reject(Object.assign(new Error('User canceled the one-time cycle transfer'),{code:'ONE_TIME_CYCLE_CALL_CANCELLED'}));};
  confirm.onclick=()=>{close();state.calls.push({method:'deposit',id:quote.requestId});const attached=quote.allowPartial?BigInt(quote.maxCyclesAtoms):BigInt(quote.amountAtoms);const operation={requestId:quote.requestId,target:quote.target,requestedCyclesAtoms:quote.amountAtoms,attachedCyclesAtoms:attached.toString(),expectedNetAtoms:(attached-BigInt(quote.feeAtoms)).toString(),feeAtoms:quote.feeAtoms,status:state.scenario==='cycles-interrupted'?'pending':'complete',ledgerBlockIndex:state.scenario==='cycles-interrupted'?null:'98765',recipientBalanceAtoms:null,error:null,createdAtNs:'1789110000000000000',updatedAtNs:'1789110000000000000',refundedCyclesAtoms:'0',chargedCyclesAtoms:attached.toString(),allowPartial:quote.allowPartial,detailsAvailable:true};put(operation);if(state.scenario==='cycles-interrupted')reject(Error('Reply interrupted after the conversion was dispatched.'));else resolve(operation);};
  dialog.append(heading,description,label,cancel,confirm);document.body.append(dialog);dialog.showModal();
});}
export async function readOperatingCyclesConversionStatus(id){state.calls.push({method:'status',id});if(state.statusErrorCode)throw Object.assign(Error('Receipt check temporarily unavailable'),{code:state.statusErrorCode});const row=state.operations.find(item=>item.requestId===id);if(!row)return null;if(state.complete&&row.status==='pending')return put({...row,status:'complete',ledgerBlockIndex:'98765'});return structuredClone(row);}
export async function listOperatingCyclesConversions({before,limit=20}={}){state.calls.push({method:'history',before});const start=before?state.operations.findIndex(row=>row.requestId===before)+1:0;const operations=state.operations.slice(start,start+limit);return{operations:structuredClone(state.scenario==='cycles-pages'?operations.map(operation=>({...operation,target:null,feeAtoms:null,expectedNetAtoms:null,ledgerBlockIndex:null,recipientBalanceAtoms:null,detailsAvailable:false,status:operation.status==='complete'?'unknown':operation.status})):operations),nextCursor:start+operations.length<state.operations.length?operations.at(-1).requestId:null,excludedCount:0};}
