[dependencies]
base = "0.8.3"
ic-certification = "0.1.1"
certified-http = "0.1.6"
stableheapbtreemap = "1.3.0"
rxmodb = "0.1.4"
motoko-hash-map = "https://github.com/ZhenyaUsenko/motoko-hash-map#master"