[dependencies]
base = "0.7.6"
motoko-hash-map = "https://github.com/ZhenyaUsenko/motoko-hash-map#master"
ic-certification = "0.1.0"
motoko-sha = "https://github.com/enzoh/motoko-sha#master"
certified-http = "0.1.1"