import { mkdir, readFile, writeFile } from "node:fs/promises";
import {
  CONNECTION_PROVIDER_SUPPORT_SCHEMA,
  CONNECTIONS_MAX_PROVIDERS_GLOBAL,
  CONNECTIONS_MAX_PROVIDERS_PER_APP,
  parseConnectionProviderSupportCatalog,
} from "neutron-tools/src/capabilities/catalog.js";

type Provider = {
  id: string;
  name: string;
  description: string;
  authorizationOrigin: string;
  scopes: Array<{ id: string; name: string; description: string }>;
};

const source: unknown = JSON.parse(
  await readFile(new URL("./providers.json", import.meta.url), "utf8")
);
if (!isRecord(source)) throw new Error("Invalid provider catalog");
assertExactKeys(source, ["providers"]);
if (!Array.isArray(source.providers)) throw new Error("Invalid provider catalog");
if (source.providers.length > CONNECTIONS_MAX_PROVIDERS_GLOBAL) {
  throw new Error("Provider catalog exceeds the Kernel support bound");
}
const providers = source.providers
  .map(validateProvider)
  .sort((left, right) => compareText(left.id, right.id));
if (new Set(providers.map((provider) => provider.id)).size !== providers.length) {
  throw new Error("Duplicate provider id");
}

const typescript = `// Generated by connections/generate.ts. Do not edit.\n` +
  `export const generatedConnectionProviders = ${JSON.stringify(providers, null, 2)} as const;\n`;

const providerSupport = parseConnectionProviderSupportCatalog({
  schema: CONNECTION_PROVIDER_SUPPORT_SCHEMA,
  providers: providers.map((provider) => ({
    provider: provider.id,
    scopes: provider.scopes.map((scope) => scope.id),
  })),
});
const providerSupportJson = `${JSON.stringify(providerSupport, null, 2)}\n`;

const motoko = `// Generated by connections/generate.ts. Do not edit.\nmodule {\n` +
  `    public type Scope = { id : Text; name : Text; description : Text };\n` +
  `    public type ProviderDescriptor = {\n` +
  `        id : Text;\n        display_name : Text;\n        description : Text;\n` +
  `        authorization_origin : Text;\n        scopes : [Scope];\n    };\n\n` +
  `    public let max_connections_per_app : Nat = ${CONNECTIONS_MAX_PROVIDERS_PER_APP};\n` +
  `    public let max_connections : Nat = ${CONNECTIONS_MAX_PROVIDERS_GLOBAL};\n\n` +
  `    public let providers : [ProviderDescriptor] = [\n` +
  providers.map((provider) => `        {\n` +
    `            id = ${motokoText(provider.id)};\n` +
    `            display_name = ${motokoText(provider.name)};\n` +
    `            description = ${motokoText(provider.description)};\n` +
    `            authorization_origin = ${motokoText(provider.authorizationOrigin)};\n` +
    `            scopes = [${provider.scopes.map((scope) => `{ id = ${motokoText(scope.id)}; name = ${motokoText(scope.name)}; description = ${motokoText(scope.description)} }`).join(", ")}];\n` +
    `        }`).join(",\n") +
  `\n    ];\n};\n`;

await mkdir(new URL("../dist/", import.meta.url), { recursive: true });
await Promise.all([
  writeFile(
    new URL("../src/connections/catalog.generated.ts", import.meta.url),
    typescript
  ),
  writeFile(
    new URL("../backend/connections/CatalogData.mo", import.meta.url),
    motoko
  ),
  writeFile(
    new URL("./provider-support.generated.json", import.meta.url),
    providerSupportJson,
  ),
  writeFile(
    new URL("../dist/connection-providers.json", import.meta.url),
    providerSupportJson,
  ),
]);

function validateProvider(value: unknown): Provider {
  if (!isRecord(value)) throw new Error("Invalid provider entry");
  assertExactKeys(value, [
    "id",
    "name",
    "description",
    "authorizationOrigin",
    "scopes",
  ]);
  const id = requiredString(value.id, "provider id", /^[a-z][a-z0-9_]{1,31}$/);
  const name = requiredString(value.name, "provider name");
  const description = requiredString(value.description, "provider description");
  const authorizationOrigin = requiredAuthorizationOrigin(
    value.authorizationOrigin,
    id,
  );
  if (!Array.isArray(value.scopes) || value.scopes.length > 32) {
    throw new Error(`Invalid scopes for ${id}`);
  }
  const scopes = value.scopes
    .map((scope) => {
      if (!isRecord(scope)) throw new Error(`Invalid scope for ${id}`);
      assertExactKeys(scope, ["id", "name", "description"]);
      return {
        id: requiredString(
          scope.id,
          "scope id",
          /^[a-zA-Z0-9._:/-]{1,80}$/,
        ),
        name: requiredString(scope.name, "scope name"),
        description: requiredString(scope.description, "scope description"),
      };
    })
    .sort((left, right) => compareText(left.id, right.id));
  if (new Set(scopes.map((scope) => scope.id)).size !== scopes.length) {
    throw new Error(`Duplicate scope for ${id}`);
  }
  return {
    id,
    name,
    description,
    authorizationOrigin,
    scopes,
  };
}

function requiredAuthorizationOrigin(value: unknown, provider: string): string {
  const text = requiredString(value, "authorization origin");
  const origin = new URL(text);
  if (
    origin.protocol !== "https:" ||
    origin.origin !== text ||
    origin.username ||
    origin.password ||
    origin.pathname !== "/" ||
    origin.search ||
    origin.hash
  ) {
    throw new Error(`Invalid authorization origin for ${provider}`);
  }
  return origin.origin;
}

function requiredString(
  value: unknown,
  label: string,
  pattern?: RegExp
): string {
  if (
    typeof value !== "string" ||
    value.length < 1 ||
    value.length > 280 ||
    (pattern && !pattern.test(value))
  ) {
    throw new Error(`Invalid ${label}`);
  }
  return value;
}

function motokoText(value: string): string {
  return JSON.stringify(value);
}

function compareText(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}

function assertExactKeys(
  value: Record<string, unknown>,
  expected: readonly string[],
): void {
  const allowed = new Set(expected);
  const keys = Object.keys(value);
  if (
    keys.length !== allowed.size ||
    keys.some((key) => !allowed.has(key))
  ) {
    throw new Error("Provider catalog contains an unknown or missing field");
  }
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
