// Generated by evm_crypto_eip712.vectors.mjs using viem hashTypedData.
// EIP-712 reference vector: https://eips.ethereum.org/EIPS/eip-712
// Digest values are independent of the Motoko encoder under test.
import Runtime "mo:core/Runtime";
import Eip712 "../backend/evm/Eip712";
import Hex "../backend/evm/Hex";

func valid(testName : Text, json : Text, digest : Text) {
    switch (Eip712.hash(json)) {
        case (#ok(actual)) {
            if (Hex.encode(actual) != digest) Runtime.trap(testName # ": unexpected digest " # Hex.encode(actual));
        };
        case (#err(reason)) Runtime.trap(testName # ": rejected valid input: " # reason);
    };
};

func invalid(testName : Text, json : Text) {
    switch (Eip712.hash(json)) {
        case (#err(_)) {};
        case (#ok(_)) Runtime.trap(testName # ": accepted invalid input");
    };
};

valid("Published Ether Mail",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"version\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"},{\"name\":\"verifyingContract\",\"type\":\"address\"}],\"Person\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"wallet\",\"type\":\"address\"}],\"Mail\":[{\"name\":\"from\",\"type\":\"Person\"},{\"name\":\"to\",\"type\":\"Person\"},{\"name\":\"contents\",\"type\":\"string\"}]},\"primaryType\":\"Mail\",\"domain\":{\"name\":\"Ether Mail\",\"version\":\"1\",\"chainId\":1,\"verifyingContract\":\"0xCcCCccccCCCCcCCCCCCcCcCccCcCCCcCcccccccC\"},\"message\":{\"from\":{\"name\":\"Cow\",\"wallet\":\"0xCD2a3d9F938E13CD947Ec05AbC7FE734Df8DD826\"},\"to\":{\"name\":\"Bob\",\"wallet\":\"0xbBbBBBBbbBBBbbbBbbBbbbbBBbBbbbbBbBbbBBbB\"},\"contents\":\"Hello, Bob!\"}}",
    "0xbe609aee343fb3c4b28e1df9e632fca64fcfaede20f02e86244efddf30957bd2",
);

valid("Nested structs and dependency sorting",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Transfer\":[{\"name\":\"owner\",\"type\":\"Person\"},{\"name\":\"asset\",\"type\":\"Asset\"},{\"name\":\"delegates\",\"type\":\"Person[]\"}],\"Person\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"wallet\",\"type\":\"address\"}],\"Asset\":[{\"name\":\"token\",\"type\":\"address\"},{\"name\":\"amount\",\"type\":\"uint256\"},{\"name\":\"metadata\",\"type\":\"Metadata\"}],\"Metadata\":[{\"name\":\"ticker\",\"type\":\"string\"},{\"name\":\"flags\",\"type\":\"bool[2]\"}]},\"primaryType\":\"Transfer\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"owner\":{\"name\":\"Alice\",\"wallet\":\"0x1111111111111111111111111111111111111111\"},\"asset\":{\"token\":\"0x2222222222222222222222222222222222222222\",\"amount\":\"123456789012345678901234567890\",\"metadata\":{\"ticker\":\"USDC\",\"flags\":[true,false]}},\"delegates\":[{\"name\":\"Bob\",\"wallet\":\"0x3333333333333333333333333333333333333333\"},{\"name\":\"Carol\",\"wallet\":\"0x4444444444444444444444444444444444444444\"}]}}",
    "0xf4c5ff7e0203176ae80f0a6b2bfd9992e633cd32935f1ffd9891f9f9ef370b5c",
);

valid("Nested fixed and dynamic arrays",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Arrays\":[{\"name\":\"matrix\",\"type\":\"uint16[2][3]\"},{\"name\":\"signed\",\"type\":\"int8[][2]\"},{\"name\":\"names\",\"type\":\"string[]\"},{\"name\":\"bytesValues\",\"type\":\"bytes[]\"},{\"name\":\"empty\",\"type\":\"address[]\"}]},\"primaryType\":\"Arrays\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"matrix\":[[1,2],[255,256],[65535,0]],\"signed\":[[-128,-1,127],[]],\"names\":[\"\",\"café\",\"東京\"],\"bytesValues\":[\"0x\",\"0x00\",\"0x123456\"],\"empty\":[]}}",
    "0xb83bb6fe5b08704d30216da3d55856d088b53f710ba17605287f50e1bf658ed3",
);

valid("Recursive schema with finite array-terminated data",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Node\":[{\"name\":\"value\",\"type\":\"uint256\"},{\"name\":\"children\",\"type\":\"Node[]\"}]},\"primaryType\":\"Node\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":\"1\",\"children\":[{\"value\":\"2\",\"children\":[]},{\"value\":\"3\",\"children\":[{\"value\":\"4\",\"children\":[]}]}]}}",
    "0xd6754ee6fc1eccbb5eacc1ddbca913d140e304f48387b2e2d814a3bed84e6b17",
);

valid("Mutually recursive schemas with finite data",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Alpha\":[{\"name\":\"label\",\"type\":\"string\"},{\"name\":\"children\",\"type\":\"Beta[]\"}],\"Beta\":[{\"name\":\"enabled\",\"type\":\"bool\"},{\"name\":\"children\",\"type\":\"Alpha[]\"}]},\"primaryType\":\"Alpha\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"label\":\"root\",\"children\":[{\"enabled\":true,\"children\":[{\"label\":\"leaf\",\"children\":[]}]}]}}",
    "0xdefdfb3ebf328f74677779d6d77c28327dab5b58353afec040be439f04bca885",
);

valid("Signed and unsigned integer boundaries",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Integers\":[{\"name\":\"smallMin\",\"type\":\"int8\"},{\"name\":\"smallMax\",\"type\":\"int8\"},{\"name\":\"min\",\"type\":\"int256\"},{\"name\":\"max\",\"type\":\"int256\"},{\"name\":\"unsigned\",\"type\":\"uint256\"},{\"name\":\"byte\",\"type\":\"uint8\"},{\"name\":\"zero\",\"type\":\"uint256\"}]},\"primaryType\":\"Integers\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"smallMin\":-128,\"smallMax\":127,\"min\":\"-57896044618658097711785492504343953926634992332820282019728792003956564819968\",\"max\":\"57896044618658097711785492504343953926634992332820282019728792003956564819967\",\"unsigned\":\"115792089237316195423570985008687907853269984665640564039457584007913129639935\",\"byte\":255,\"zero\":0}}",
    "0xfa48e91de7816bf6a8e054dfe8281345763cb014a96aee0cd84523d2f386fb09",
);

valid("Fixed bytes right padding and dynamic bytes hashing",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Bytes\":[{\"name\":\"one\",\"type\":\"bytes1\"},{\"name\":\"two\",\"type\":\"bytes2\"},{\"name\":\"full\",\"type\":\"bytes32\"},{\"name\":\"dynamic\",\"type\":\"bytes\"},{\"name\":\"empty\",\"type\":\"bytes\"}]},\"primaryType\":\"Bytes\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"one\":\"0xff\",\"two\":\"0x0123\",\"full\":\"0x000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f\",\"dynamic\":\"0x000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f202122\",\"empty\":\"0x\"}}",
    "0x0266cd14fe94e17d28abcf00ef7e99dcd0cb3bae6604c4678aaf411726a146df",
);

valid("Unicode UTF-8, whitespace and JSON escapes",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"string\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":\"café 東京 😀\\n\\\"quote\\\"\\\\slash\\t\"}}",
    "0x89c629e5204fb2bf3c776a05e92a461ae8eeb3b94f0a788c574c0be883a42613",
);

valid("Escaped Unicode and a valid surrogate pair have identical bytes",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"string\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":\"caf\\u00e9 \\u6771\\u4eac \\ud83d\\ude00\\n\\\"quote\\\"\\\\slash\\t\"}}",
    "0x89c629e5204fb2bf3c776a05e92a461ae8eeb3b94f0a788c574c0be883a42613",
);

valid("JSON member order and insignificant whitespace do not change digest",
    "{\n  \"message\": {\n    \"from\": {\n      \"name\": \"Cow\",\n      \"wallet\": \"0xCD2a3d9F938E13CD947Ec05AbC7FE734Df8DD826\"\n    },\n    \"to\": {\n      \"name\": \"Bob\",\n      \"wallet\": \"0xbBbBBBBbbBBBbbbBbbBbbbbBBbBbbbbBbBbbBBbB\"\n    },\n    \"contents\": \"Hello, Bob!\"\n  },\n  \"domain\": {\n    \"name\": \"Ether Mail\",\n    \"version\": \"1\",\n    \"chainId\": 1,\n    \"verifyingContract\": \"0xCcCCccccCCCCcCCCCCCcCcCccCcCCCcCcccccccC\"\n  },\n  \"primaryType\": \"Mail\",\n  \"types\": {\n    \"EIP712Domain\": [\n      {\n        \"name\": \"name\",\n        \"type\": \"string\"\n      },\n      {\n        \"name\": \"version\",\n        \"type\": \"string\"\n      },\n      {\n        \"name\": \"chainId\",\n        \"type\": \"uint256\"\n      },\n      {\n        \"name\": \"verifyingContract\",\n        \"type\": \"address\"\n      }\n    ],\n    \"Person\": [\n      {\n        \"name\": \"name\",\n        \"type\": \"string\"\n      },\n      {\n        \"name\": \"wallet\",\n        \"type\": \"address\"\n      }\n    ],\n    \"Mail\": [\n      {\n        \"name\": \"from\",\n        \"type\": \"Person\"\n      },\n      {\n        \"name\": \"to\",\n        \"type\": \"Person\"\n      },\n      {\n        \"name\": \"contents\",\n        \"type\": \"string\"\n      }\n    ]\n  }\n}",
    "0xbe609aee343fb3c4b28e1df9e632fca64fcfaede20f02e86244efddf30957bd2",
);

valid("Decimal integer strings",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"int256\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":\"-1000\"}}",
    "0xd5a77a25043b55375c8c684c545419cdb9476789096e32099a04e13144970020",
);

valid("Decimal JSON integer numbers",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"int256\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":-1000}}",
    "0xd5a77a25043b55375c8c684c545419cdb9476789096e32099a04e13144970020",
);

valid("Full-width uint256 JSON integer preserves every digit",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint256\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":115792089237316195423570985008687907853269984665640564039457584007913129639935}}",
    "0x010270102b700e6089628be6d19b7f8ef273989e1cbd9fc3d8a244876b931288",
);

valid("Full-width int256 JSON integer preserves every digit",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"int256\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":-57896044618658097711785492504343953926634992332820282019728792003956564819968}}",
    "0xb30fa494c42f310cc65b84546bdbffb19d1d1e83123d40e1f2495f76915abba8",
);

valid("An integral decimal and exponent are encoded exactly",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint256\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":1.25e2}}",
    "0x453abdcc521ed8dc931f45389484794c36fc27afb9951e77e017a4d59bb42045",
);

valid("An integral decimal without exponent is encoded exactly",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint256\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":125.000}}",
    "0x453abdcc521ed8dc931f45389484794c36fc27afb9951e77e017a4d59bb42045",
);

valid("A negative exponent can still represent an integer",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"int256\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":-1250e-1}}",
    "0x5abf08a59129dd02b796bc549f84bc6d0bfbe96eef03fc1a22005409a5e89631",
);

valid("Zero with an enormous positive exponent is still zero",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint256\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":0e999999999999999999999999999999999999999999999999999999999999}}",
    "0x1e686709a6be12c26e7abbcd1325e543900cb62b2b4fc3a3f5bdd59838e21703",
);

valid("Zero with an enormous negative exponent is still zero",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint256\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":-0.000e-999999999999999999999999999999999999999999999999999999999999}}",
    "0x1e686709a6be12c26e7abbcd1325e543900cb62b2b4fc3a3f5bdd59838e21703",
);

valid("Domain-only typed data",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}]},\"primaryType\":\"EIP712Domain\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{}}",
    "0xe4714e1943d8211c08b8874ff292a06ef967a6d8302f8905a27f5971cf302963",
);

valid("A chain-neutral EIP-712 domain hashes without inventing a chain",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint256\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Chain-neutral protocol\"},\"message\":{\"value\":\"1\"}}",
    "0x31b0d18101a99e8fb5e5aff7bd78af91cdec88476f02ef8723467eb12675ab50",
);

valid("Hyperliquid approved trading signer with exact qualified primary type",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"version\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"},{\"name\":\"verifyingContract\",\"type\":\"address\"}],\"HyperliquidTransaction:ApproveAgent\":[{\"name\":\"hyperliquidChain\",\"type\":\"string\"},{\"name\":\"agentAddress\",\"type\":\"address\"},{\"name\":\"agentName\",\"type\":\"string\"},{\"name\":\"nonce\",\"type\":\"uint64\"}]},\"primaryType\":\"HyperliquidTransaction:ApproveAgent\",\"domain\":{\"name\":\"HyperliquidSignTransaction\",\"version\":\"1\",\"chainId\":42161,\"verifyingContract\":\"0x0000000000000000000000000000000000000000\"},\"message\":{\"hyperliquidChain\":\"Testnet\",\"agentAddress\":\"0x1111111111111111111111111111111111111111\",\"agentName\":\"neutron-research\",\"nonce\":1788820000000}}",
    "0x80742b882ad5ba923c11dc9c2b320213d317ee149e25cf8959178dfecece9bd9",
);

valid("Hyperliquid mainnet approval has a different environment digest",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"version\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"},{\"name\":\"verifyingContract\",\"type\":\"address\"}],\"HyperliquidTransaction:ApproveAgent\":[{\"name\":\"hyperliquidChain\",\"type\":\"string\"},{\"name\":\"agentAddress\",\"type\":\"address\"},{\"name\":\"agentName\",\"type\":\"string\"},{\"name\":\"nonce\",\"type\":\"uint64\"}]},\"primaryType\":\"HyperliquidTransaction:ApproveAgent\",\"domain\":{\"name\":\"HyperliquidSignTransaction\",\"version\":\"1\",\"chainId\":42161,\"verifyingContract\":\"0x0000000000000000000000000000000000000000\"},\"message\":{\"hyperliquidChain\":\"Mainnet\",\"agentAddress\":\"0x1111111111111111111111111111111111111111\",\"agentName\":\"neutron-research\",\"nonce\":1788820000000}}",
    "0xb6eb65eda606d530cef8161f5d381929eb38d8fa65d8e6102de5b0fb98e7dcb9",
);

valid("HyperCore perps USDC withdrawal to Ethereum",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"version\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"},{\"name\":\"verifyingContract\",\"type\":\"address\"}],\"HyperliquidTransaction:SendToEvmWithData\":[{\"name\":\"hyperliquidChain\",\"type\":\"string\"},{\"name\":\"token\",\"type\":\"string\"},{\"name\":\"amount\",\"type\":\"string\"},{\"name\":\"sourceDex\",\"type\":\"string\"},{\"name\":\"destinationRecipient\",\"type\":\"string\"},{\"name\":\"addressEncoding\",\"type\":\"string\"},{\"name\":\"destinationChainId\",\"type\":\"uint32\"},{\"name\":\"gasLimit\",\"type\":\"uint64\"},{\"name\":\"data\",\"type\":\"bytes\"},{\"name\":\"nonce\",\"type\":\"uint64\"}]},\"primaryType\":\"HyperliquidTransaction:SendToEvmWithData\",\"domain\":{\"name\":\"HyperliquidSignTransaction\",\"version\":\"1\",\"chainId\":42161,\"verifyingContract\":\"0x0000000000000000000000000000000000000000\"},\"message\":{\"hyperliquidChain\":\"Mainnet\",\"token\":\"USDC\",\"amount\":\"12.345678\",\"sourceDex\":\"\",\"destinationRecipient\":\"0x1234567890123456789012345678901234567890\",\"addressEncoding\":\"hex\",\"destinationChainId\":0,\"gasLimit\":\"200000\",\"data\":\"0x\",\"nonce\":\"1788820000001\"}}",
    "0xdb453b024e00c7080003ec48309ee9602cbb6104cf8331d475b7467fd82efb0a",
);

invalid("Duplicate top-level JSON key",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint8\"}]},\"primaryType\":\"Value\",\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":1}}",
);

invalid("Duplicate struct JSON member",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint8\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":1,\"value\":2}}",
);

invalid("Duplicate type declaration JSON key",
    "{\"types\":{\"Value\":[], \"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint8\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":1}}",
);

invalid("Duplicate declaration field JSON key",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"name\":\"other\",\"type\":\"uint8\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":1}}",
);

invalid("Duplicate struct member declaration",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint8\"},{\"name\":\"value\",\"type\":\"uint8\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":1}}",
);

invalid("An unknown message member must not be silently unsigned",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint8\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":1,\"extra\":\"this text would not be signed\"}}",
);

invalid("An unknown domain member must not be silently unsigned",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint8\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161,\"extra\":\"this text would not be signed\"},\"message\":{\"value\":1}}",
);

invalid("Invalid or unresolved type uint",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":1}}",
);

invalid("Invalid or unresolved type int",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"int\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":1}}",
);

invalid("Invalid or unresolved type uint0",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint0\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":1}}",
);

invalid("Invalid or unresolved type uint7",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint7\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":1}}",
);

invalid("Invalid or unresolved type uint264",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint264\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":1}}",
);

invalid("Invalid or unresolved type int9",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"int9\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":1}}",
);

invalid("Invalid or unresolved type bytes0",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"bytes0\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":1}}",
);

invalid("Invalid or unresolved type bytes33",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"bytes33\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":1}}",
);

invalid("Invalid or unresolved type UnknownStruct",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"UnknownStruct\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":1}}",
);

invalid("Invalid or unresolved type uint8[",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint8[\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":1}}",
);

invalid("Invalid or unresolved type uint8]",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint8]\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":1}}",
);

invalid("Invalid or unresolved type uint8[-1]",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint8[-1]\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":1}}",
);

invalid("Invalid or unresolved type uint8[1]junk",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint8[1]junk\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":1}}",
);

invalid("Invalid or unresolved type uint8[][]junk",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint8[][]junk\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":1}}",
);

invalid("Missing referenced type",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"Missing[]\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":[]}}",
);

invalid("An invalid type identifier",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Bad-Name\":[{\"name\":\"value\",\"type\":\"uint8\"}]},\"primaryType\":\"Bad-Name\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":1}}",
);

invalid("An invalid member identifier",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"bad-name\",\"type\":\"uint8\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"bad-name\":1}}",
);

invalid("Qualified names are not accepted as field names",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"scope:value\",\"type\":\"uint8\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"scope:value\":1}}",
);

invalid("Invalid qualified struct name :Value",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\":Value\":[{\"name\":\"value\",\"type\":\"uint8\"}]},\"primaryType\":\":Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":1}}",
);

invalid("Invalid qualified struct name Value:",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value:\":[{\"name\":\"value\",\"type\":\"uint8\"}]},\"primaryType\":\"Value:\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":1}}",
);

invalid("Invalid qualified struct name Protocol::Value",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Protocol::Value\":[{\"name\":\"value\",\"type\":\"uint8\"}]},\"primaryType\":\"Protocol::Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":1}}",
);

invalid("Invalid qualified struct name Protocol:9Value",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Protocol:9Value\":[{\"name\":\"value\",\"type\":\"uint8\"}]},\"primaryType\":\"Protocol:9Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":1}}",
);

invalid("Invalid qualified struct name Protocol:Bad-Name",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Protocol:Bad-Name\":[{\"name\":\"value\",\"type\":\"uint8\"}]},\"primaryType\":\"Protocol:Bad-Name\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":1}}",
);

invalid("Invalid qualified struct name Protocol:Value(uint256)",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Protocol:Value(uint256)\":[{\"name\":\"value\",\"type\":\"uint8\"}]},\"primaryType\":\"Protocol:Value(uint256)\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":1}}",
);

invalid("Invalid qualified struct name Protocol:Value,Other",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Protocol:Value,Other\":[{\"name\":\"value\",\"type\":\"uint8\"}]},\"primaryType\":\"Protocol:Value,Other\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":1}}",
);

invalid("Invalid qualified struct name Protocol: Value",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Protocol: Value\":[{\"name\":\"value\",\"type\":\"uint8\"}]},\"primaryType\":\"Protocol: Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":1}}",
);

invalid("Invalid uint8 value -1",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint8\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":-1}}",
);

invalid("Invalid uint8 value 256",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint8\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":256}}",
);

invalid("Invalid int8 value -129",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"int8\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":-129}}",
);

invalid("Invalid int8 value 128",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"int8\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":128}}",
);

invalid("Invalid uint256 value \"115792089237316195423570985008687907853269984665640564039457584007913129639936\"",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint256\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":\"115792089237316195423570985008687907853269984665640564039457584007913129639936\"}}",
);

invalid("Invalid int256 value \"57896044618658097711785492504343953926634992332820282019728792003956564819968\"",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"int256\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":\"57896044618658097711785492504343953926634992332820282019728792003956564819968\"}}",
);

invalid("Invalid int256 value \"-57896044618658097711785492504343953926634992332820282019728792003956564819969\"",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"int256\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":\"-57896044618658097711785492504343953926634992332820282019728792003956564819969\"}}",
);

invalid("Invalid uint256 value \"1.5\"",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint256\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":\"1.5\"}}",
);

invalid("Invalid uint256 value \"NaN\"",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint256\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":\"NaN\"}}",
);

invalid("Invalid uint256 value 1.5",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint256\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":1.5}}",
);

invalid("Invalid bool value \"true\"",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"bool\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":\"true\"}}",
);

invalid("Invalid bool value 1",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"bool\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":1}}",
);

invalid("Invalid address value \"0x1234\"",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"address\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":\"0x1234\"}}",
);

invalid("Invalid address value \"0xgg11111111111111111111111111111111111111\"",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"address\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":\"0xgg11111111111111111111111111111111111111\"}}",
);

invalid("Invalid bytes1 value \"0x\"",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"bytes1\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":\"0x\"}}",
);

invalid("Invalid bytes1 value \"0x1234\"",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"bytes1\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":\"0x1234\"}}",
);

invalid("Invalid bytes2 value \"0x12\"",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"bytes2\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":\"0x12\"}}",
);

invalid("Invalid bytes value \"0x1\"",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"bytes\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":\"0x1\"}}",
);

invalid("Invalid bytes value \"0xzz\"",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"bytes\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":\"0xzz\"}}",
);

invalid("Invalid string value 123",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"string\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":123}}",
);

invalid("Fixed array is too short",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint8[2]\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":[1]}}",
);

invalid("Fixed array is too long",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint8[2]\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":[1,2,3]}}",
);

invalid("A nested fixed array has a wrong inner dimension",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint8[2][2]\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":[[1,2],[3]]}}",
);

invalid("An array value must be an array",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint8[]\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":1}}",
);

invalid("An array integer still enforces its width",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint8[]\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":[1,256]}}",
);

invalid("Nonzero huge exponent or fractional JSON integer 1e999999999999999999999999999999999999999999999999999999999999",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint256\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":1e999999999999999999999999999999999999999999999999999999999999}}",
);

invalid("Nonzero huge exponent or fractional JSON integer 1e-999999999999999999999999999999999999999999999999999999999999",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint256\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":1e-999999999999999999999999999999999999999999999999999999999999}}",
);

invalid("Nonzero huge exponent or fractional JSON integer 1.25e1",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint256\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":1.25e1}}",
);

invalid("Nonzero huge exponent or fractional JSON integer 1250e-2",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint256\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":1250e-2}}",
);

invalid("Nonzero huge exponent or fractional JSON integer 0.00001",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint256\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":0.00001}}",
);

invalid("A required field may not be null",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint8\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":null}}",
);

invalid("Missing required message field",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint8\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{}}",
);

invalid("Message cannot be null",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint8\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":null}",
);

invalid("Domain cannot be null",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint8\"}]},\"primaryType\":\"Value\",\"domain\":null,\"message\":{\"value\":1}}",
);

invalid("Missing message",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint8\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161}}",
);

invalid("Missing domain",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint8\"}]},\"primaryType\":\"Value\",\"message\":{\"value\":1}}",
);

invalid("Missing types",
    "{\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":1}}",
);

invalid("Missing domain type",
    "{\"types\":{\"Value\":[{\"name\":\"value\",\"type\":\"uint8\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":1}}",
);

invalid("Missing primary type",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint8\"}]},\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":1}}",
);

invalid("Unknown primary type",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint8\"}]},\"primaryType\":\"Unknown\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":1}}",
);

invalid("Malformed JSON: trailing comma",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint8\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":1,}}",
);

invalid("Malformed JSON: trailing text",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint8\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":1}} false",
);

invalid("Malformed JSON: truncated document",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint8\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":1}",
);

invalid("Malformed JSON: unescaped control character",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"string\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":\"\u{1}\"}}",
);

invalid("Malformed Unicode escape \\ud800",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"string\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":\"\\ud800\"}}",
);

invalid("Malformed Unicode escape \\udfff",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"string\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":\"\\udfff\"}}",
);

invalid("Malformed Unicode escape \\ud800\\u0041",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"string\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":\"\\ud800\\u0041\"}}",
);

invalid("Malformed Unicode escape \\ud800\\ud800",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"string\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":\"\\ud800\\ud800\"}}",
);

invalid("Malformed Unicode escape \\uqqqq",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"string\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":\"\\uqqqq\"}}",
);

invalid("Malformed Unicode escape \\u123",
    "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"}],\"Value\":[{\"name\":\"value\",\"type\":\"string\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Neutron EIP-712 vectors\",\"chainId\":42161},\"message\":{\"value\":\"\\u123\"}}",
);

// The wallet-selected chain must agree with the chain actually signed.
switch (Eip712.hashForChain("{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"version\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"},{\"name\":\"verifyingContract\",\"type\":\"address\"}],\"HyperliquidTransaction:ApproveAgent\":[{\"name\":\"hyperliquidChain\",\"type\":\"string\"},{\"name\":\"agentAddress\",\"type\":\"address\"},{\"name\":\"agentName\",\"type\":\"string\"},{\"name\":\"nonce\",\"type\":\"uint64\"}]},\"primaryType\":\"HyperliquidTransaction:ApproveAgent\",\"domain\":{\"name\":\"HyperliquidSignTransaction\",\"version\":\"1\",\"chainId\":42161,\"verifyingContract\":\"0x0000000000000000000000000000000000000000\"},\"message\":{\"hyperliquidChain\":\"Testnet\",\"agentAddress\":\"0x1111111111111111111111111111111111111111\",\"agentName\":\"neutron-research\",\"nonce\":1788820000000}}", 42161)) {
    case (#ok(value)) assert (Hex.encode(value) == "0x80742b882ad5ba923c11dc9c2b320213d317ee149e25cf8959178dfecece9bd9");
    case (#err(reason)) Runtime.trap("Rejected Hyperliquid signing on supported Arbitrum context: " # reason);
};
switch (Eip712.hashForChain("{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"version\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"},{\"name\":\"verifyingContract\",\"type\":\"address\"}],\"HyperliquidTransaction:ApproveAgent\":[{\"name\":\"hyperliquidChain\",\"type\":\"string\"},{\"name\":\"agentAddress\",\"type\":\"address\"},{\"name\":\"agentName\",\"type\":\"string\"},{\"name\":\"nonce\",\"type\":\"uint64\"}]},\"primaryType\":\"HyperliquidTransaction:ApproveAgent\",\"domain\":{\"name\":\"HyperliquidSignTransaction\",\"version\":\"1\",\"chainId\":42161,\"verifyingContract\":\"0x0000000000000000000000000000000000000000\"},\"message\":{\"hyperliquidChain\":\"Testnet\",\"agentAddress\":\"0x1111111111111111111111111111111111111111\",\"agentName\":\"neutron-research\",\"nonce\":1788820000000}}", 1)) {
    case (#err(_)) {};
    case (#ok(_)) Runtime.trap("Qualified types bypassed selected-chain binding");
};
switch (Eip712.hashForChain("{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"version\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"},{\"name\":\"verifyingContract\",\"type\":\"address\"}],\"HyperliquidTransaction:SendToEvmWithData\":[{\"name\":\"hyperliquidChain\",\"type\":\"string\"},{\"name\":\"token\",\"type\":\"string\"},{\"name\":\"amount\",\"type\":\"string\"},{\"name\":\"sourceDex\",\"type\":\"string\"},{\"name\":\"destinationRecipient\",\"type\":\"string\"},{\"name\":\"addressEncoding\",\"type\":\"string\"},{\"name\":\"destinationChainId\",\"type\":\"uint32\"},{\"name\":\"gasLimit\",\"type\":\"uint64\"},{\"name\":\"data\",\"type\":\"bytes\"},{\"name\":\"nonce\",\"type\":\"uint64\"}]},\"primaryType\":\"HyperliquidTransaction:SendToEvmWithData\",\"domain\":{\"name\":\"HyperliquidSignTransaction\",\"version\":\"1\",\"chainId\":42161,\"verifyingContract\":\"0x0000000000000000000000000000000000000000\"},\"message\":{\"hyperliquidChain\":\"Mainnet\",\"token\":\"USDC\",\"amount\":\"12.345678\",\"sourceDex\":\"\",\"destinationRecipient\":\"0x1234567890123456789012345678901234567890\",\"addressEncoding\":\"hex\",\"destinationChainId\":0,\"gasLimit\":\"200000\",\"data\":\"0x\",\"nonce\":\"1788820000001\"}}", 42161)) {
    case (#ok(value)) assert (Hex.encode(value) == "0xdb453b024e00c7080003ec48309ee9602cbb6104cf8331d475b7467fd82efb0a");
    case (#err(reason)) Runtime.trap("Rejected Hyperliquid signing on supported Arbitrum context: " # reason);
};
switch (Eip712.hashForChain("{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"version\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"},{\"name\":\"verifyingContract\",\"type\":\"address\"}],\"HyperliquidTransaction:SendToEvmWithData\":[{\"name\":\"hyperliquidChain\",\"type\":\"string\"},{\"name\":\"token\",\"type\":\"string\"},{\"name\":\"amount\",\"type\":\"string\"},{\"name\":\"sourceDex\",\"type\":\"string\"},{\"name\":\"destinationRecipient\",\"type\":\"string\"},{\"name\":\"addressEncoding\",\"type\":\"string\"},{\"name\":\"destinationChainId\",\"type\":\"uint32\"},{\"name\":\"gasLimit\",\"type\":\"uint64\"},{\"name\":\"data\",\"type\":\"bytes\"},{\"name\":\"nonce\",\"type\":\"uint64\"}]},\"primaryType\":\"HyperliquidTransaction:SendToEvmWithData\",\"domain\":{\"name\":\"HyperliquidSignTransaction\",\"version\":\"1\",\"chainId\":42161,\"verifyingContract\":\"0x0000000000000000000000000000000000000000\"},\"message\":{\"hyperliquidChain\":\"Mainnet\",\"token\":\"USDC\",\"amount\":\"12.345678\",\"sourceDex\":\"\",\"destinationRecipient\":\"0x1234567890123456789012345678901234567890\",\"addressEncoding\":\"hex\",\"destinationChainId\":0,\"gasLimit\":\"200000\",\"data\":\"0x\",\"nonce\":\"1788820000001\"}}", 1)) {
    case (#err(_)) {};
    case (#ok(_)) Runtime.trap("Qualified types bypassed selected-chain binding");
};
let mail = "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"version\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"},{\"name\":\"verifyingContract\",\"type\":\"address\"}],\"Person\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"wallet\",\"type\":\"address\"}],\"Mail\":[{\"name\":\"from\",\"type\":\"Person\"},{\"name\":\"to\",\"type\":\"Person\"},{\"name\":\"contents\",\"type\":\"string\"}]},\"primaryType\":\"Mail\",\"domain\":{\"name\":\"Ether Mail\",\"version\":\"1\",\"chainId\":1,\"verifyingContract\":\"0xCcCCccccCCCCcCCCCCCcCcCccCcCCCcCcccccccC\"},\"message\":{\"from\":{\"name\":\"Cow\",\"wallet\":\"0xCD2a3d9F938E13CD947Ec05AbC7FE734Df8DD826\"},\"to\":{\"name\":\"Bob\",\"wallet\":\"0xbBbBBBBbbBBBbbbBbbBbbbbBBbBbbbbBbBbbBBbB\"},\"contents\":\"Hello, Bob!\"}}";
switch (Eip712.hashForChain(mail, 1)) {
    case (#ok(value)) assert (Hex.encode(value) == "0xbe609aee343fb3c4b28e1df9e632fca64fcfaede20f02e86244efddf30957bd2");
    case (#err(reason)) Runtime.trap("Expected matching chain: " # reason);
};
switch (Eip712.hashForChain(mail, 42161)) {
    case (#err(_)) {};
    case (#ok(_)) Runtime.trap("Accepted mismatched EIP-712 chain");
};
switch (Eip712.hashForChain("{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"}],\"Value\":[{\"name\":\"value\",\"type\":\"uint256\"}]},\"primaryType\":\"Value\",\"domain\":{\"name\":\"Chain-neutral protocol\"},\"message\":{\"value\":\"1\"}}", 1)) {
    case (#ok(value)) assert (Hex.encode(value) == "0x31b0d18101a99e8fb5e5aff7bd78af91cdec88476f02ef8723467eb12675ab50");
    case (#err(reason)) Runtime.trap("Rejected valid chain-neutral typed data: " # reason);
};
