// Regenerate: node apps/evm_wallet/test/generate_erc20_fixtures.mjs
// Verify:     node apps/evm_wallet/test/generate_erc20_fixtures.mjs --check
// Independent references: viem ABI/EIP-1559 encoding and noble secp256k1.
import assert from 'node:assert/strict';
import { readFile, writeFile } from 'node:fs/promises';
import { secp256k1 } from '@noble/curves/secp256k1';
import {
  encodeFunctionData,
  keccak256,
  parseAbi,
  parseTransaction,
  recoverTransactionAddress,
  serializeTransaction,
} from 'viem';

const privateKey = '0'.repeat(63) + '1'; // Same public fixture key as BackendFixtures.
const spender = '0x0000000000000000000000000000000000000003';
const approveData = encodeFunctionData({
  abi: parseAbi(['function approve(address spender, uint256 amount) returns (bool)']),
  functionName: 'approve',
  args: [spender, 100n],
});
assert.equal(approveData, '0x095ea7b3' + '3'.padStart(64, '0') + '64'.padStart(64, '0'));

const transaction = {
  type: 'eip1559',
  chainId: 1,
  nonce: 0,
  gas: 21000n,
  to: '0x0000000000000000000000000000000000000002',
  value: 0n,
  data: approveData,
  maxFeePerGas: 100n,
  maxPriorityFeePerGas: 2n,
  accessList: [],
};
const approveDigest = keccak256(serializeTransaction(transaction));
const signature = secp256k1.sign(approveDigest.slice(2), privateKey, { lowS: true });
assert(signature.recovery === 0 || signature.recovery === 1);
const approveSignature = '0x' + signature.toCompactHex();
assert.equal(approveSignature.length, 2 + 64 * 2);
assert(secp256k1.verify(signature, approveDigest.slice(2), secp256k1.getPublicKey(privateKey)));
const approveRaw = serializeTransaction(transaction, {
  r: '0x' + signature.r.toString(16).padStart(64, '0'),
  s: '0x' + signature.s.toString(16).padStart(64, '0'),
  yParity: signature.recovery,
});
const approveHash = keccak256(approveRaw);
assert.equal(
  (await recoverTransactionAddress({ serializedTransaction: approveRaw })).toLowerCase(),
  '0x7e5f4552091a69125d5dfcb7b8c2659029395bdf',
);
const decoded = parseTransaction(approveRaw);
for (const [field, value] of Object.entries(transaction)) {
  // viem omits optional zero/empty fields when decoding their canonical RLP.
  const actual = field === 'value' ? (decoded.value ?? 0n)
    : field === 'accessList' ? (decoded.accessList ?? [])
    : decoded[field];
  assert.deepEqual(actual, value, `signed transaction ${field}`);
}

const fields = { approveData, approveDigest, approveSignature, approveRaw, approveHash };
const output = '// Independent viem/noble vectors generated by generate_erc20_fixtures.mjs.\n'
  + 'module {\n'
  + Object.entries(fields).map(([name, value]) => `    public let ${name} : Text = "${value}";`).join('\n')
  + '\n};\n';
const destination = new URL('./ERC20Fixtures.mo', import.meta.url);
if (process.argv.includes('--check')) {
  assert.equal(await readFile(destination, 'utf8'), output, 'ERC20 fixtures match reference implementations');
  console.log('ERC20 fixtures verified');
} else {
  await writeFile(destination, output);
  console.log('ERC20 fixtures generated');
}
