// Regenerate the deterministic Motoko vectors with:
//   node apps/evm_wallet/test/generate_secp_vectors.mjs > /tmp/evm_crypto_secp_test.mo
// Compare that file with evm_crypto_secp_test.mo before replacing it.
// Independent reference implementations: @noble/curves 1.9.7 and viem 2.55.1.
import assert from 'node:assert/strict';
import { secp256k1 as curve } from '@noble/curves/secp256k1';
import { keccak256, stringToHex } from 'viem';
import { publicKeyToAddress } from 'viem/accounts';

const { n, p } = curve.CURVE;
const h32 = (n) => n.toString(16).padStart(64, '0');
const signatureHex = (r, s) => h32(r) + h32(s);
const vectors = [
  ['generator, digest one', 1n, h32(1n)],
  ['independent key and message digest', 2n, keccak256(stringToHex('Neutron EVM wallet')).slice(2)],
  ['zero digest', 1n, h32(0n)],
  ['digest equal to group order', 1n, h32(n)],
  ['digest greater than group order', 1n, h32(n + 1n)],
  ['negated generator, maximum digest', n - 1n, 'ff'.repeat(32)],
].map(([label, privateKey, digest]) => {
  const point = curve.ProjectivePoint.fromPrivateKey(h32(privateKey));
  const signed = curve.sign(digest, h32(privateKey), { lowS: true });
  const lowS = signatureHex(signed.r, signed.s);
  const highS = signatureHex(signed.r, n - signed.s);
  assert(curve.verify(lowS, digest, point.toHex(true)));
  assert(curve.verify(highS, digest, point.toHex(true), { lowS: false }));
  assert(signed.recoverPublicKey(digest).equals(point));
  assert(new curve.Signature(signed.r, n - signed.s, signed.recovery ^ 1).recoverPublicKey(digest).equals(point));
  return {
    label, digest, lowS, highS,
    pub: point.toHex(true), uncompressed: point.toHex(false),
    x: h32(point.x), y: h32(point.y),
    address: publicKeyToAddress(`0x${point.toHex(false)}`).toLowerCase(),
    r: h32(signed.r), s: h32(signed.s), parity: signed.recovery,
  };
});

// Construct a valid but Ethereum-unrepresentable signature. Choose R.x = n+2,
// then derive Q = r^-1(sR-zG), with z=s=1 and r=2. This gives recovery ID 2.
// Random signing would practically never encounter this valid ECDSA corner case.
const overflowR = curve.ProjectivePoint.fromHex(`02${h32(n + 2n)}`);
const overflowQ = overflowR.subtract(curve.ProjectivePoint.BASE).multiply(curve.ProjectivePoint.Fn.inv(2n));
const overflowRaw = signatureHex(2n, 1n);
assert(curve.verify(overflowRaw, h32(1n), overflowQ.toHex(true)));
assert(new curve.Signature(2n, 1n, 2).recoverPublicKey(h32(1n)).equals(overflowQ));
assert(!new curve.Signature(2n, 1n, 0).recoverPublicKey(h32(1n)).equals(overflowQ));

const one = vectors[0];
const corruptRaw = signatureHex(BigInt(`0x${one.r}`) + 1n, BigInt(`0x${one.s}`));
assert(!curve.verify(corruptRaw, one.digest, one.pub));
assert(!curve.verify(one.lowS, h32(2n), one.pub));
assert(!curve.verify(signatureHex(1n, 1n), h32(1n), vectors[5].pub));
const malformedKeys = [
  ['empty', ''],
  ['SEC1 point at infinity', '00'],
  ['short compressed', one.pub.slice(0, -2)],
  ['long compressed', `${one.pub}00`],
  ['short uncompressed', one.uncompressed.slice(0, -2)],
  ['long uncompressed', `${one.uncompressed}00`],
  ['unsupported prefix', `05${one.x}`],
  ['hybrid prefix', `06${one.x}${one.y}`],
  ['compressed x equal to field prime', `02${h32(p)}`],
  ['compressed x beyond field prime', `03${h32(p + 1n)}`],
  ['compressed x is a nonresidue', `02${h32(0n)}`],
  ['uncompressed x equal to field prime', `04${h32(p)}${one.y}`],
  ['uncompressed y equal to field prime', `04${one.x}${h32(p)}`],
  ['uncompressed point off curve', `04${one.x}${h32(BigInt(`0x${one.y}`) + 1n)}`],
  ['uncompressed zero point', `04${h32(0n)}${h32(0n)}`],
];
for (const [label, key] of malformedKeys) {
  assert.throws(() => curve.ProjectivePoint.fromHex(key), undefined, label);
}

let output = `// Generated by generate_secp_vectors.mjs. Independent noble/curves and viem vectors.
// These exercise SEC1 parsing, Ethereum address derivation, low-S normalization,
// signature verification and the rare ECDSA recovery-ID 2/3 exclusion.
import Blob "mo:core/Blob";
import Runtime "mo:core/Runtime";
import Hex "../backend/evm/Hex";
import Secp256k1 "../backend/evm/Secp256k1";

func bytes(value : Text) : Blob {
    switch (Hex.decode("0x" # value)) {
        case (#ok(value)) value;
        case (#err(message)) Runtime.trap("bad test vector: " # message);
    };
};

func expectNormalized(caseName : Text, publicKey : Text, digest : Text, raw : Text, r : Nat, s : Nat, parity : Nat) {
    switch (Secp256k1.normalizeSignature(bytes(publicKey), bytes(digest), bytes(raw))) {
        case (#ok(actual)) {
            if (actual.r != r or actual.s != s or actual.yParity != parity) {
                Runtime.trap("wrong normalized signature: " # caseName);
            };
        };
        case (#err(message)) Runtime.trap("signature rejected: " # caseName # ": " # message);
    };
};

func expectRejected(caseName : Text, publicKey : Text, digest : Text, raw : Text) {
    switch (Secp256k1.normalizeSignature(bytes(publicKey), bytes(digest), bytes(raw))) {
        case (#err(_)) {};
        case (#ok(_)) Runtime.trap("invalid signature accepted: " # caseName);
    };
};

func expectPublicKey(caseName : Text, publicKey : Text, x : Nat, y : Nat, address : Text) {
    switch (Secp256k1.decompressPublicKey(bytes(publicKey))) {
        case (#ok(actual)) {
            if (actual.x != x or actual.y != y) Runtime.trap("wrong point: " # caseName);
        };
        case (#err(message)) Runtime.trap("public key rejected: " # caseName # ": " # message);
    };
    switch (Secp256k1.address(bytes(publicKey))) {
        case (#ok(actual)) {
            if (actual != address) Runtime.trap("wrong address: " # caseName);
        };
        case (#err(message)) Runtime.trap("address rejected: " # caseName # ": " # message);
    };
};

func expectMalformedKey(caseName : Text, publicKey : Text) {
    switch (Secp256k1.decompressPublicKey(bytes(publicKey))) {
        case (#err(_)) {};
        case (#ok(_)) Runtime.trap("malformed public key accepted: " # caseName);
    };
    switch (Secp256k1.address(bytes(publicKey))) {
        case (#err(_)) {};
        case (#ok(_)) Runtime.trap("malformed public key address accepted: " # caseName);
    };
};

`;

for (const vector of vectors) {
  output += `// ${vector.label}. High-S input must yield the same canonical Ethereum signature.\n`;
  output += `expectPublicKey("${vector.label} compressed", "${vector.pub}", 0x${vector.x}, 0x${vector.y}, "${vector.address}");\n`;
  output += `expectPublicKey("${vector.label} uncompressed", "${vector.uncompressed}", 0x${vector.x}, 0x${vector.y}, "${vector.address}");\n`;
  for (const [kind, raw] of [['low-S', vector.lowS], ['high-S', vector.highS]]) {
    output += `expectNormalized("${vector.label} ${kind}", "${vector.pub}", "${vector.digest}", "${raw}", 0x${vector.r}, 0x${vector.s}, ${vector.parity});\n`;
  }
  output += '\n';
}
output += `// Uncompressed keys are accepted for signature verification too.\n`;
output += `expectNormalized("uncompressed signer", "${one.uncompressed}", "${one.digest}", "${one.lowS}", 0x${one.r}, 0x${one.s}, ${one.parity});\n\n`;

output += `// Valid ECDSA signatures whose R.x = n+2 require recovery IDs 2/3 and cannot\n// be represented by Ethereum's parity-only signature format.\n`;
output += `expectPublicKey("overflow signer", "${overflowQ.toHex(true)}", 0x${h32(overflowQ.x)}, 0x${h32(overflowQ.y)}, "${publicKeyToAddress(`0x${overflowQ.toHex(false)}`).toLowerCase()}");\n`;
output += `expectRejected("R.x >= n low-S", "${overflowQ.toHex(true)}", "${h32(1n)}", "${overflowRaw}");\n`;
output += `expectRejected("R.x >= n high-S", "${overflowQ.toHex(true)}", "${h32(1n)}", "${signatureHex(2n, n - 1n)}");\n\n`;

for (const [label, key] of malformedKeys) {
  output += `expectMalformedKey("${label}", "${key}");\n`;
  output += `expectRejected("${label}", "${key}", "${one.digest}", "${one.lowS}");\n`;
}
output += '\n';
for (const [label, digest, raw, pub] of [
  ['empty digest', '', one.lowS, one.pub],
  ['short digest', one.digest.slice(2), one.lowS, one.pub],
  ['long digest', `${one.digest}00`, one.lowS, one.pub],
  ['empty signature', one.digest, '', one.pub],
  ['short signature', one.digest, one.lowS.slice(2), one.pub],
  ['long signature', one.digest, `${one.lowS}00`, one.pub],
  ['zero r', one.digest, signatureHex(0n, 1n), one.pub],
  ['r equal to group order', one.digest, signatureHex(n, 1n), one.pub],
  ['r above group order', one.digest, signatureHex(n + 1n, 1n), one.pub],
  ['zero s', one.digest, signatureHex(1n, 0n), one.pub],
  ['s equal to group order', one.digest, signatureHex(1n, n), one.pub],
  ['s above group order', one.digest, signatureHex(1n, n + 1n), one.pub],
  ['changed r', one.digest, corruptRaw, one.pub],
  ['different digest', h32(2n), one.lowS, one.pub],
  ['different signer', one.digest, one.lowS, vectors[5].pub],
  ['recovered R is infinity', h32(1n), signatureHex(1n, 1n), vectors[5].pub],
]) {
  output += `expectRejected("${label}", "${pub}", "${digest}", "${raw}");\n`;
}
process.stdout.write(output);
