import { secp256k1 } from '@noble/curves/secp256k1';
import {serializeTransaction, keccak256, hashMessage} from 'viem';
import {writeFile} from 'node:fs/promises';
const priv='0'.repeat(63)+'1';
const vectors=[];
for (const [chainId,nonce,maxFee] of [[1,0,100],[1,1,100],[42161,0,100],[1,0,200]]) {
 const tx={type:'eip1559',chainId,nonce,gas:21000n,maxFeePerGas:BigInt(maxFee),maxPriorityFeePerGas:2n,to:'0x0000000000000000000000000000000000000002',value:1n,data:'0x',accessList:[]};
 const digest=keccak256(serializeTransaction(tx));const sig=secp256k1.sign(digest.slice(2),priv,{lowS:true});
 const raw=serializeTransaction(tx,{r:'0x'+sig.r.toString(16).padStart(64,'0'),s:'0x'+sig.s.toString(16).padStart(64,'0'),yParity:sig.recovery});
 vectors.push({digest,signature:'0x'+sig.toCompactHex(),raw,hash:keccak256(raw)});
}
const digest=hashMessage({raw:'0x6869'}); const sig=secp256k1.sign(digest.slice(2),priv,{lowS:true});vectors.push({digest,signature:'0x'+sig.toCompactHex(),raw:'0x',hash:'0x'});
const legacyTx = {type:'legacy', chainId:11155111, nonce:0, gas:21000n, gasPrice:100n, to:'0x0000000000000000000000000000000000000002', value:1n, data:'0x'};
const legacyDigest=keccak256(serializeTransaction(legacyTx)); const legacySig=secp256k1.sign(legacyDigest.slice(2),priv,{lowS:true});
const legacyRaw=serializeTransaction(legacyTx,{r:'0x'+legacySig.r.toString(16).padStart(64,'0'),s:'0x'+legacySig.s.toString(16).padStart(64,'0'),v:BigInt(legacySig.recovery + 27)});
vectors.push({digest:legacyDigest,signature:'0x'+legacySig.toCompactHex(),raw:legacyRaw,hash:keccak256(legacyRaw)});
const vals=vectors.map(v=>`{digest="${v.digest}";signature="${v.signature}";raw="${v.raw}";hash="${v.hash}"}`).join(',\n');
await writeFile(new URL('./BackendFixtures.mo', import.meta.url),`// Independent viem/noble vectors generated by generate_backend_fixtures.mjs.\nmodule { public let publicKey = "0x${secp256k1.getPublicKey(priv,true).reduce((s,b)=>s+b.toString(16).padStart(2,'0'),'')}"; public let vectors : [{digest:Text;signature:Text;raw:Text;hash:Text}] = [${vals}]; };\n`);
