// Generated by connections/generate.ts. Do not edit.
module {
    public type Scope = { id : Text; name : Text; description : Text };
    public type ProviderDescriptor = {
        id : Text;
        display_name : Text;
        description : Text;
        authorization_origin : Text;
        scopes : [Scope];
    };

    public let max_connections_per_app : Nat = 8;
    public let max_connections : Nat = 256;

    public let providers : [ProviderDescriptor] = [
        {
            id = "openrouter";
            display_name = "OpenRouter";
            description = "OpenRouter models and user-controlled API key";
            authorization_origin = "https://openrouter.ai";
            scopes = [];
        }
    ];
};
